export const TABLA_PROFESIONALES = "profesionales";

export const CAMPOS = {
  nombre: "Nombre_y_apellido",
  profesion: "Profesion",
  matricula: "Matricula",
  genero: "Genero",
  cobertura: "Obra_social",
  modalidad: "Modalidad",
  ubicacion: "Ubicacion",
  motivo: "Motivo_de_consulta",
  foto_url: "photo",
  whatsapp: "Whatsapp",
  destacado: "Destacado",
  descripcion: "Descripcion",
} as const;

export type Profesional = Record<string, string | number | boolean | null>;

export const PROVINCIAS = [
  "Buenos Aires",
  "CABA",
  "Catamarca",
  "Chaco",
  "Chubut",
  "Córdoba",
  "Corrientes",
  "Entre Ríos",
  "Formosa",
  "Jujuy",
  "La Pampa",
  "La Rioja",
  "Mendoza",
  "Misiones",
  "Neuquén",
  "Río Negro",
  "Salta",
  "San Juan",
  "San Luis",
  "Santa Cruz",
  "Santa Fe",
  "Santiago del Estero",
  "Tierra del Fuego",
  "Tucumán",
];

export const CIUDADES_POR_PROVINCIA: Record<string, string[]> = {
  "Buenos Aires": [
    "La Plata",
    "Mar del Plata",
    "Bahía Blanca",
    "Tandil",
    "San Isidro",
    "Vicente López",
    "Avellaneda",
    "Quilmes",
    "Lomas de Zamora",
    "Morón",
    "San Martín",
    "Pilar",
    "Tigre",
    "Escobar",
    "Otras localidades",
  ],
  CABA: [
    "Agronomía",
    "Almagro",
    "Balvanera",
    "Belgrano",
    "Caballito",
    "Colegiales",
    "Flores",
    "La Boca",
    "Nuñez",
    "Palermo",
    "Recoleta",
    "Retiro",
    "San Telmo",
    "Villa Urquiza",
    "Otras comunas",
  ],
  Córdoba: [
    "Córdoba Capital",
    "Villa Carlos Paz",
    "Río Cuarto",
    "Villa María",
    "San Francisco",
    "Alta Gracia",
    "Otras localidades",
  ],
  "Santa Fe": [
    "Rosario",
    "Santa Fe Capital",
    "Rafaela",
    "Venado Tuerto",
    "Reconquista",
    "Otras localidades",
  ],
  Mendoza: [
    "Mendoza Capital",
    "Godoy Cruz",
    "Guaymallén",
    "San Rafael",
    "Maipú",
    "Otras localidades",
  ],
  Tucumán: ["San Miguel de Tucumán", "Yerba Buena", "Tafí Viejo", "Otras localidades"],
  Salta: ["Salta Capital", "San Ramón de la Nueva Orán", "Cafayate", "Otras localidades"],
  "Entre Ríos": ["Paraná", "Gualeguaychú", "Concordia", "Otras localidades"],
};
