-- Provincias (24, incluye CABA) -- fuente: API oficial Georef (datos.gob.ar)
insert into public.provinces (id) values
  ('Buenos Aires'),
  ('CABA'),
  ('Catamarca'),
  ('Chaco'),
  ('Chubut'),
  ('Corrientes'),
  ('Córdoba'),
  ('Entre Ríos'),
  ('Formosa'),
  ('Jujuy'),
  ('La Pampa'),
  ('La Rioja'),
  ('Mendoza'),
  ('Misiones'),
  ('Neuquén'),
  ('Río Negro'),
  ('Salta'),
  ('San Juan'),
  ('San Luis'),
  ('Santa Cruz'),
  ('Santa Fe'),
  ('Santiago del Estero'),
  ('Tierra del Fuego'),
  ('Tucumán');

-- Ciudades / municipios oficiales por provincia (2256 filas) -- fuente: API oficial Georef,
-- resource municipios (https://apis.datos.gob.ar/georef/api/municipios), con localidades como
-- fallback para Santa Cruz y Santiago del Estero (esas dos provincias no tienen municipios
-- formales en el registro oficial).
insert into public.cities (province_id, name) values
  ('Buenos Aires', '25 de Mayo'),
  ('Buenos Aires', '9 de Julio'),
  ('Buenos Aires', 'Adolfo Alsina'),
  ('Buenos Aires', 'Adolfo Gonzales Chaves'),
  ('Buenos Aires', 'Alberti'),
  ('Buenos Aires', 'Almirante Brown'),
  ('Buenos Aires', 'Arrecifes'),
  ('Buenos Aires', 'Avellaneda'),
  ('Buenos Aires', 'Ayacucho'),
  ('Buenos Aires', 'Azul'),
  ('Buenos Aires', 'Bahía Blanca'),
  ('Buenos Aires', 'Balcarce'),
  ('Buenos Aires', 'Baradero'),
  ('Buenos Aires', 'Benito Juárez'),
  ('Buenos Aires', 'Berazategui'),
  ('Buenos Aires', 'Berisso'),
  ('Buenos Aires', 'Bolívar'),
  ('Buenos Aires', 'Bragado'),
  ('Buenos Aires', 'Brandsen'),
  ('Buenos Aires', 'Campana'),
  ('Buenos Aires', 'Cañuelas'),
  ('Buenos Aires', 'Capitán Sarmiento'),
  ('Buenos Aires', 'Carlos Casares'),
  ('Buenos Aires', 'Carlos Tejedor'),
  ('Buenos Aires', 'Carmen de Areco'),
  ('Buenos Aires', 'Castelli'),
  ('Buenos Aires', 'Chacabuco'),
  ('Buenos Aires', 'Chascomús'),
  ('Buenos Aires', 'Chivilcoy'),
  ('Buenos Aires', 'Colón'),
  ('Buenos Aires', 'Coronel de Marina Leonardo Rosales'),
  ('Buenos Aires', 'Coronel Dorrego'),
  ('Buenos Aires', 'Coronel Pringles'),
  ('Buenos Aires', 'Coronel Suárez'),
  ('Buenos Aires', 'Daireaux'),
  ('Buenos Aires', 'Dolores'),
  ('Buenos Aires', 'Ensenada'),
  ('Buenos Aires', 'Escobar'),
  ('Buenos Aires', 'Esteban Echeverría'),
  ('Buenos Aires', 'Exaltación de la Cruz'),
  ('Buenos Aires', 'Ezeiza'),
  ('Buenos Aires', 'Florencio Varela'),
  ('Buenos Aires', 'Florentino Ameghino'),
  ('Buenos Aires', 'General Alvarado'),
  ('Buenos Aires', 'General Alvear'),
  ('Buenos Aires', 'General Arenales'),
  ('Buenos Aires', 'General Belgrano'),
  ('Buenos Aires', 'General Guido'),
  ('Buenos Aires', 'General Juan Madariaga'),
  ('Buenos Aires', 'General La Madrid'),
  ('Buenos Aires', 'General Las Heras'),
  ('Buenos Aires', 'General Lavalle'),
  ('Buenos Aires', 'General Paz'),
  ('Buenos Aires', 'General Pinto'),
  ('Buenos Aires', 'General Pueyrredón'),
  ('Buenos Aires', 'General Rodríguez'),
  ('Buenos Aires', 'General San Martín'),
  ('Buenos Aires', 'General Viamonte'),
  ('Buenos Aires', 'General Villegas'),
  ('Buenos Aires', 'Guaminí'),
  ('Buenos Aires', 'Hipólito Yrigoyen'),
  ('Buenos Aires', 'Hurlingham'),
  ('Buenos Aires', 'Ituzaingó'),
  ('Buenos Aires', 'José C. Paz'),
  ('Buenos Aires', 'Junín'),
  ('Buenos Aires', 'La Costa'),
  ('Buenos Aires', 'La Matanza'),
  ('Buenos Aires', 'La Plata'),
  ('Buenos Aires', 'Lanús'),
  ('Buenos Aires', 'Laprida'),
  ('Buenos Aires', 'Las Flores'),
  ('Buenos Aires', 'Leandro N. Alem'),
  ('Buenos Aires', 'Lezama'),
  ('Buenos Aires', 'Lincoln'),
  ('Buenos Aires', 'Lobería'),
  ('Buenos Aires', 'Lobos'),
  ('Buenos Aires', 'Lomas de Zamora'),
  ('Buenos Aires', 'Luján'),
  ('Buenos Aires', 'Magdalena'),
  ('Buenos Aires', 'Maipú'),
  ('Buenos Aires', 'Malvinas Argentinas'),
  ('Buenos Aires', 'Mar Chiquita'),
  ('Buenos Aires', 'Marcos Paz'),
  ('Buenos Aires', 'Mercedes'),
  ('Buenos Aires', 'Merlo'),
  ('Buenos Aires', 'Monte'),
  ('Buenos Aires', 'Monte Hermoso'),
  ('Buenos Aires', 'Moreno'),
  ('Buenos Aires', 'Morón'),
  ('Buenos Aires', 'Navarro'),
  ('Buenos Aires', 'Necochea'),
  ('Buenos Aires', 'Olavarría'),
  ('Buenos Aires', 'Patagones'),
  ('Buenos Aires', 'Pehuajó'),
  ('Buenos Aires', 'Pellegrini'),
  ('Buenos Aires', 'Pergamino'),
  ('Buenos Aires', 'Pila'),
  ('Buenos Aires', 'Pilar'),
  ('Buenos Aires', 'Pinamar'),
  ('Buenos Aires', 'Presidente Perón'),
  ('Buenos Aires', 'Puán'),
  ('Buenos Aires', 'Punta Indio'),
  ('Buenos Aires', 'Quilmes'),
  ('Buenos Aires', 'Ramallo'),
  ('Buenos Aires', 'Rauch'),
  ('Buenos Aires', 'Rivadavia'),
  ('Buenos Aires', 'Rojas'),
  ('Buenos Aires', 'Roque Pérez'),
  ('Buenos Aires', 'Saavedra'),
  ('Buenos Aires', 'Saladillo'),
  ('Buenos Aires', 'Salliqueló'),
  ('Buenos Aires', 'Salto'),
  ('Buenos Aires', 'San Andrés de Giles'),
  ('Buenos Aires', 'San Antonio de Areco'),
  ('Buenos Aires', 'San Cayetano'),
  ('Buenos Aires', 'San Fernando'),
  ('Buenos Aires', 'San Isidro'),
  ('Buenos Aires', 'San Miguel'),
  ('Buenos Aires', 'San Nicolás'),
  ('Buenos Aires', 'San Pedro'),
  ('Buenos Aires', 'San Vicente'),
  ('Buenos Aires', 'Suipacha'),
  ('Buenos Aires', 'Tandil'),
  ('Buenos Aires', 'Tapalqué'),
  ('Buenos Aires', 'Tigre'),
  ('Buenos Aires', 'Tordillo'),
  ('Buenos Aires', 'Tornquist'),
  ('Buenos Aires', 'Trenque Lauquen'),
  ('Buenos Aires', 'Tres Arroyos'),
  ('Buenos Aires', 'Tres de Febrero'),
  ('Buenos Aires', 'Tres Lomas'),
  ('Buenos Aires', 'Vicente López'),
  ('Buenos Aires', 'Villa Gesell'),
  ('Buenos Aires', 'Villarino'),
  ('Buenos Aires', 'Zárate'),
  ('CABA', 'Comuna 1'),
  ('CABA', 'Comuna 10'),
  ('CABA', 'Comuna 11'),
  ('CABA', 'Comuna 12'),
  ('CABA', 'Comuna 13'),
  ('CABA', 'Comuna 14'),
  ('CABA', 'Comuna 15'),
  ('CABA', 'Comuna 2'),
  ('CABA', 'Comuna 3'),
  ('CABA', 'Comuna 4'),
  ('CABA', 'Comuna 5'),
  ('CABA', 'Comuna 6'),
  ('CABA', 'Comuna 7'),
  ('CABA', 'Comuna 8'),
  ('CABA', 'Comuna 9'),
  ('Catamarca', 'Aconquija'),
  ('Catamarca', 'Ancasti'),
  ('Catamarca', 'Andalgalá'),
  ('Catamarca', 'Antofagasta de la Sierra'),
  ('Catamarca', 'Belén'),
  ('Catamarca', 'Capayán'),
  ('Catamarca', 'Corral Quemado'),
  ('Catamarca', 'El Alto'),
  ('Catamarca', 'El Rodeo'),
  ('Catamarca', 'Fiambalá'),
  ('Catamarca', 'Fray Mamerto Esquiú'),
  ('Catamarca', 'Hualfin'),
  ('Catamarca', 'Huillapima'),
  ('Catamarca', 'Icaño'),
  ('Catamarca', 'La Puerta'),
  ('Catamarca', 'Las Juntas'),
  ('Catamarca', 'Londres'),
  ('Catamarca', 'Los Altos'),
  ('Catamarca', 'Los Varela'),
  ('Catamarca', 'Mutquin'),
  ('Catamarca', 'Paclín'),
  ('Catamarca', 'Pomán'),
  ('Catamarca', 'Pozo de Piedra'),
  ('Catamarca', 'Puerta de Corral Quemado'),
  ('Catamarca', 'Puerta de San José'),
  ('Catamarca', 'Recreo'),
  ('Catamarca', 'San Fernando'),
  ('Catamarca', 'San Fernando del Valle de Catamarca'),
  ('Catamarca', 'San José'),
  ('Catamarca', 'Santa María'),
  ('Catamarca', 'Santa Rosa'),
  ('Catamarca', 'Saujil'),
  ('Catamarca', 'Tapso'),
  ('Catamarca', 'Tinogasta'),
  ('Catamarca', 'Valle Viejo'),
  ('Catamarca', 'Villa Vil'),
  ('Chaco', 'Avia Terai'),
  ('Chaco', 'Barranqueras'),
  ('Chaco', 'Basail'),
  ('Chaco', 'Campo Largo'),
  ('Chaco', 'Capitán Solari'),
  ('Chaco', 'Charadai'),
  ('Chaco', 'Charata'),
  ('Chaco', 'Chorotis'),
  ('Chaco', 'Ciervo Petiso'),
  ('Chaco', 'Colonia Benítez'),
  ('Chaco', 'Colonia Elisa'),
  ('Chaco', 'Colonia Popular'),
  ('Chaco', 'Colonias Unidas'),
  ('Chaco', 'Concepción del Bermejo'),
  ('Chaco', 'Coronel Du Graty'),
  ('Chaco', 'Corzuela'),
  ('Chaco', 'Cote Lai'),
  ('Chaco', 'El Sauzalito'),
  ('Chaco', 'Enrique Urién'),
  ('Chaco', 'Fontana'),
  ('Chaco', 'Fuerte Esperanza'),
  ('Chaco', 'Gancedo'),
  ('Chaco', 'General Capdevila'),
  ('Chaco', 'General Pinedo'),
  ('Chaco', 'General San Martín'),
  ('Chaco', 'General Vedia'),
  ('Chaco', 'Hermoso Campo'),
  ('Chaco', 'Isla del Cerrito'),
  ('Chaco', 'Juan José Castelli'),
  ('Chaco', 'La Clotilde'),
  ('Chaco', 'La Eduvigis'),
  ('Chaco', 'La Escondida'),
  ('Chaco', 'La Leonesa'),
  ('Chaco', 'La Tigra'),
  ('Chaco', 'La Verde'),
  ('Chaco', 'Laguna Blanca'),
  ('Chaco', 'Laguna Limpia'),
  ('Chaco', 'Lapachito'),
  ('Chaco', 'Las Breñas'),
  ('Chaco', 'Las Garcitas'),
  ('Chaco', 'Las Palmas'),
  ('Chaco', 'Los Frentones'),
  ('Chaco', 'Machagai'),
  ('Chaco', 'Makallé'),
  ('Chaco', 'Margarita Belén'),
  ('Chaco', 'Miraflores'),
  ('Chaco', 'Misión Nueva Pompeya'),
  ('Chaco', 'Napenay'),
  ('Chaco', 'Pampa Almirón'),
  ('Chaco', 'Pampa del Indio'),
  ('Chaco', 'Pampa del Infierno'),
  ('Chaco', 'Presidencia de la Plaza'),
  ('Chaco', 'Presidencia Roca'),
  ('Chaco', 'Presidencia Roque Sáenz Peña'),
  ('Chaco', 'Puerto Bermejo'),
  ('Chaco', 'Puerto Eva Perón'),
  ('Chaco', 'Puerto Tirol'),
  ('Chaco', 'Puerto Vilelas'),
  ('Chaco', 'Quitilipi'),
  ('Chaco', 'Resistencia'),
  ('Chaco', 'Samuhú'),
  ('Chaco', 'San Bernardo'),
  ('Chaco', 'Santa Sylvina'),
  ('Chaco', 'Taco Pozo'),
  ('Chaco', 'Tres Isletas'),
  ('Chaco', 'Villa Ángela'),
  ('Chaco', 'Villa Berthet'),
  ('Chaco', 'Villa Río Bermejito'),
  ('Chubut', '28 de Julio'),
  ('Chubut', 'Aldea Beleiro'),
  ('Chubut', 'Aldea Epulef'),
  ('Chubut', 'Alto Río Senguer'),
  ('Chubut', 'Buen Pasto'),
  ('Chubut', 'Camarones'),
  ('Chubut', 'Carrenleufú'),
  ('Chubut', 'Cerro Centinela'),
  ('Chubut', 'Cholila'),
  ('Chubut', 'Colan Conhue'),
  ('Chubut', 'Comodoro Rivadavia'),
  ('Chubut', 'Corcovado'),
  ('Chubut', 'Cushamen'),
  ('Chubut', 'Dique Florentino Ameghino'),
  ('Chubut', 'Doctor Ricardo Rojas'),
  ('Chubut', 'Dolavon'),
  ('Chubut', 'Dr. Atilio Oscar Viglione'),
  ('Chubut', 'El Hoyo'),
  ('Chubut', 'El Maitén'),
  ('Chubut', 'Epuyén'),
  ('Chubut', 'Esquel'),
  ('Chubut', 'Facundo'),
  ('Chubut', 'Gaiman'),
  ('Chubut', 'Gan Gan'),
  ('Chubut', 'Gastre'),
  ('Chubut', 'Gobernador Costa'),
  ('Chubut', 'Gualjaina'),
  ('Chubut', 'José de San Martín'),
  ('Chubut', 'Lago Blanco'),
  ('Chubut', 'Lago Puelo'),
  ('Chubut', 'Lagunita Salada'),
  ('Chubut', 'Las Plumas'),
  ('Chubut', 'Los Altares'),
  ('Chubut', 'Paso de Indios'),
  ('Chubut', 'Paso del Sapo'),
  ('Chubut', 'Puerto Madryn'),
  ('Chubut', 'Puerto Pirámides'),
  ('Chubut', 'Rada Tilly'),
  ('Chubut', 'Rawson'),
  ('Chubut', 'Río Mayo'),
  ('Chubut', 'Río Pico'),
  ('Chubut', 'Sarmiento'),
  ('Chubut', 'Tecka'),
  ('Chubut', 'Telsen'),
  ('Chubut', 'Trelew'),
  ('Chubut', 'Trevelin'),
  ('Córdoba', 'Achiras'),
  ('Córdoba', 'Adelia María'),
  ('Córdoba', 'Agua de Oro'),
  ('Córdoba', 'Alcira'),
  ('Córdoba', 'Aldea Santa María'),
  ('Córdoba', 'Alejandro Roca'),
  ('Córdoba', 'Alejo Ledesma'),
  ('Córdoba', 'Alicia'),
  ('Córdoba', 'Almafuerte'),
  ('Córdoba', 'Alpa Corral'),
  ('Córdoba', 'Alta Gracia'),
  ('Córdoba', 'Alto Alegre'),
  ('Córdoba', 'Alto de los Quebrachos'),
  ('Córdoba', 'Altos de Chipión'),
  ('Córdoba', 'Amboy'),
  ('Córdoba', 'Ambul'),
  ('Córdoba', 'Ana Zumarán'),
  ('Córdoba', 'Anisacate'),
  ('Córdoba', 'Arias'),
  ('Córdoba', 'Arroyito'),
  ('Córdoba', 'Arroyo Algodón'),
  ('Córdoba', 'Arroyo Cabral'),
  ('Córdoba', 'Arroyo de los Patos'),
  ('Córdoba', 'Assunta'),
  ('Córdoba', 'Atahona'),
  ('Córdoba', 'Ausonia'),
  ('Córdoba', 'Avellaneda'),
  ('Córdoba', 'Ballesteros'),
  ('Córdoba', 'Ballesteros Sud'),
  ('Córdoba', 'Balnearia'),
  ('Córdoba', 'Bañado de Soto'),
  ('Córdoba', 'Bell Ville'),
  ('Córdoba', 'Bengolea'),
  ('Córdoba', 'Benjamín Gould'),
  ('Córdoba', 'Berrotarán'),
  ('Córdoba', 'Bialet Massé'),
  ('Córdoba', 'Bouwer'),
  ('Córdoba', 'Brinkmann'),
  ('Córdoba', 'Buchardo'),
  ('Córdoba', 'Bulnes'),
  ('Córdoba', 'Cabalango'),
  ('Córdoba', 'Calchín'),
  ('Córdoba', 'Calchín Oeste'),
  ('Córdoba', 'Camilo Aldao'),
  ('Córdoba', 'Caminiaga'),
  ('Córdoba', 'Canals'),
  ('Córdoba', 'Candelaria Sud'),
  ('Córdoba', 'Cañada de Luque'),
  ('Córdoba', 'Cañada de Machado'),
  ('Córdoba', 'Cañada de Río Pinto'),
  ('Córdoba', 'Cañada del Sauce'),
  ('Córdoba', 'Capilla de los Remedios'),
  ('Córdoba', 'Capilla de Sitón'),
  ('Córdoba', 'Capilla del Carmen'),
  ('Córdoba', 'Capilla del Monte'),
  ('Córdoba', 'Capitán General Bernardo O''Higgins'),
  ('Córdoba', 'Carnerillo'),
  ('Córdoba', 'Carrilobo'),
  ('Córdoba', 'Casa Grande'),
  ('Córdoba', 'Cavanagh'),
  ('Córdoba', 'Cerro Colorado'),
  ('Córdoba', 'Chaján'),
  ('Córdoba', 'Chalacea'),
  ('Córdoba', 'Chancani'),
  ('Córdoba', 'Chañar Viejo'),
  ('Córdoba', 'Charbonier'),
  ('Córdoba', 'Charras'),
  ('Córdoba', 'Chazón'),
  ('Córdoba', 'Chilibroste'),
  ('Córdoba', 'Chucul'),
  ('Córdoba', 'Chuña'),
  ('Córdoba', 'Chuña Huasi'),
  ('Córdoba', 'Churqui Cañada'),
  ('Córdoba', 'Ciénaga del Coro'),
  ('Córdoba', 'Cintra'),
  ('Córdoba', 'Colazo'),
  ('Córdoba', 'Colonia Almada'),
  ('Córdoba', 'Colonia Anita'),
  ('Córdoba', 'Colonia Barge'),
  ('Córdoba', 'Colonia Bismarck'),
  ('Córdoba', 'Colonia Bremen'),
  ('Córdoba', 'Colonia Caroya'),
  ('Córdoba', 'Colonia Italiana'),
  ('Córdoba', 'Colonia Iturraspe'),
  ('Córdoba', 'Colonia Las Cuatro Esquinas'),
  ('Córdoba', 'Colonia Las Pichanas'),
  ('Córdoba', 'Colonia Marina'),
  ('Córdoba', 'Colonia Prosperidad'),
  ('Córdoba', 'Colonia San Bartolomé'),
  ('Córdoba', 'Colonia San Pedro'),
  ('Córdoba', 'Colonia Tirolesa'),
  ('Córdoba', 'Colonia Valtelina'),
  ('Córdoba', 'Colonia Vicente Agüero'),
  ('Córdoba', 'Colonia Videla'),
  ('Córdoba', 'Colonia Vignaud'),
  ('Córdoba', 'Comechingones'),
  ('Córdoba', 'Conlara'),
  ('Córdoba', 'Copacabana'),
  ('Córdoba', 'Córdoba'),
  ('Córdoba', 'Coronel Baigorria'),
  ('Córdoba', 'Coronel Moldes'),
  ('Córdoba', 'Corral de Bustos Ifflinger'),
  ('Córdoba', 'Corralito'),
  ('Córdoba', 'Cosquín'),
  ('Córdoba', 'Costa Sacate'),
  ('Córdoba', 'Cruz Alta'),
  ('Córdoba', 'Cruz de Caña'),
  ('Córdoba', 'Cruz del Eje'),
  ('Córdoba', 'Cuesta Blanca'),
  ('Córdoba', 'Dalmacio Vélez'),
  ('Córdoba', 'Deán Funes'),
  ('Córdoba', 'Del Campillo'),
  ('Córdoba', 'Despeñaderos'),
  ('Córdoba', 'Devoto'),
  ('Córdoba', 'Diego de Rojas'),
  ('Córdoba', 'Dique Chico'),
  ('Córdoba', 'El Arañado'),
  ('Córdoba', 'El Brete'),
  ('Córdoba', 'El Chacho'),
  ('Córdoba', 'El Crispín'),
  ('Córdoba', 'El Fortín'),
  ('Córdoba', 'El Manzano'),
  ('Córdoba', 'El Rastreador'),
  ('Córdoba', 'El Rodeo'),
  ('Córdoba', 'El Tío'),
  ('Córdoba', 'Elena'),
  ('Córdoba', 'Embalse'),
  ('Córdoba', 'Esquina'),
  ('Córdoba', 'Estación General Paz'),
  ('Córdoba', 'Estación Juárez Celman'),
  ('Córdoba', 'Estancia de Guadalupe'),
  ('Córdoba', 'Estancia Vieja'),
  ('Córdoba', 'Etruria'),
  ('Córdoba', 'Eufrasio Loza'),
  ('Córdoba', 'Falda del Carmen'),
  ('Córdoba', 'Freyre'),
  ('Córdoba', 'General Baldissera'),
  ('Córdoba', 'General Cabrera'),
  ('Córdoba', 'General Deheza'),
  ('Córdoba', 'General Fotheringham'),
  ('Córdoba', 'General Levalle'),
  ('Córdoba', 'General Roca'),
  ('Córdoba', 'Guanaco Muerto'),
  ('Córdoba', 'Guasapampa'),
  ('Córdoba', 'Guatimozín'),
  ('Córdoba', 'Gutemberg'),
  ('Córdoba', 'Hernando'),
  ('Córdoba', 'Huanchilla'),
  ('Córdoba', 'Huerta Grande'),
  ('Córdoba', 'Huinca Renancó'),
  ('Córdoba', 'Idiazábal'),
  ('Córdoba', 'Impira'),
  ('Córdoba', 'Inriville'),
  ('Córdoba', 'Isla Verde'),
  ('Córdoba', 'Italó'),
  ('Córdoba', 'James Craik'),
  ('Córdoba', 'Jesús María'),
  ('Córdoba', 'Jovita'),
  ('Córdoba', 'Justiniano Posse'),
  ('Córdoba', 'Kilómetro 658'),
  ('Córdoba', 'La Batea'),
  ('Córdoba', 'La Calera'),
  ('Córdoba', 'La Carlota'),
  ('Córdoba', 'La Carolina El Potosí'),
  ('Córdoba', 'La Cautiva'),
  ('Córdoba', 'La Cesira'),
  ('Córdoba', 'La Cruz'),
  ('Córdoba', 'La Cumbre'),
  ('Córdoba', 'La Cumbrecita'),
  ('Córdoba', 'La Falda'),
  ('Córdoba', 'La Francia'),
  ('Córdoba', 'La Granja'),
  ('Córdoba', 'La Higuera'),
  ('Córdoba', 'La Laguna'),
  ('Córdoba', 'La Paisanita'),
  ('Córdoba', 'La Palestina'),
  ('Córdoba', 'La Pampa'),
  ('Córdoba', 'La Paquita'),
  ('Córdoba', 'La Para'),
  ('Córdoba', 'La Paz'),
  ('Córdoba', 'La Playa'),
  ('Córdoba', 'La Playosa'),
  ('Córdoba', 'La Población'),
  ('Córdoba', 'La Posta'),
  ('Córdoba', 'La Puerta'),
  ('Córdoba', 'La Quinta'),
  ('Córdoba', 'La Rancherita'),
  ('Córdoba', 'La Rinconada'),
  ('Córdoba', 'La Serranita'),
  ('Córdoba', 'La Tordilla'),
  ('Córdoba', 'Laborde'),
  ('Córdoba', 'Laboulaye'),
  ('Córdoba', 'Laguna Larga'),
  ('Córdoba', 'Las Acequias'),
  ('Córdoba', 'Las Albahacas'),
  ('Córdoba', 'Las Arrias'),
  ('Córdoba', 'Las Bajadas'),
  ('Córdoba', 'Las Caleras'),
  ('Córdoba', 'Las Calles'),
  ('Córdoba', 'Las Cañadas'),
  ('Córdoba', 'Las Gramillas'),
  ('Córdoba', 'Las Higueras'),
  ('Córdoba', 'Las Isletillas'),
  ('Córdoba', 'Las Junturas'),
  ('Córdoba', 'Las Palmas'),
  ('Córdoba', 'Las Peñas'),
  ('Córdoba', 'Las Peñas Sud'),
  ('Córdoba', 'Las Perdices'),
  ('Córdoba', 'Las Playas'),
  ('Córdoba', 'Las Rabonas'),
  ('Córdoba', 'Las Saladas'),
  ('Córdoba', 'Las Tapias'),
  ('Córdoba', 'Las Varas'),
  ('Córdoba', 'Las Varillas'),
  ('Córdoba', 'Las Vertientes'),
  ('Córdoba', 'Leguizamón'),
  ('Córdoba', 'Leones'),
  ('Córdoba', 'Los Cedros'),
  ('Córdoba', 'Los Cerrillos'),
  ('Córdoba', 'Los Chañaritos'),
  ('Córdoba', 'Los Cisnes'),
  ('Córdoba', 'Los Cocos'),
  ('Córdoba', 'Los Cóndores'),
  ('Córdoba', 'Los Hornillos'),
  ('Córdoba', 'Los Hoyos'),
  ('Córdoba', 'Los Mistoles'),
  ('Córdoba', 'Los Molinos'),
  ('Córdoba', 'Los Pozos'),
  ('Córdoba', 'Los Reartes'),
  ('Córdoba', 'Los Surgentes'),
  ('Córdoba', 'Los Talares'),
  ('Córdoba', 'Los Zorros'),
  ('Córdoba', 'Lozada'),
  ('Córdoba', 'Luca'),
  ('Córdoba', 'Lucio Victorio Mansilla'),
  ('Córdoba', 'Luque'),
  ('Córdoba', 'Lutti'),
  ('Córdoba', 'Luyaba'),
  ('Córdoba', 'Malagueño'),
  ('Córdoba', 'Malena'),
  ('Córdoba', 'Malvinas Argentinas'),
  ('Córdoba', 'Manfredi'),
  ('Córdoba', 'Maquinista Gallini'),
  ('Córdoba', 'Marcos Juárez'),
  ('Córdoba', 'Marull'),
  ('Córdoba', 'Matorrales'),
  ('Córdoba', 'Mattaldi'),
  ('Córdoba', 'Mayu Sumaj'),
  ('Córdoba', 'Media Naranja'),
  ('Córdoba', 'Melo'),
  ('Córdoba', 'Mendiolaza'),
  ('Córdoba', 'Mi Granja'),
  ('Córdoba', 'Mina Clavero'),
  ('Córdoba', 'Miramar de Ansenuza'),
  ('Córdoba', 'Monte Buey'),
  ('Córdoba', 'Monte de los Gauchos'),
  ('Córdoba', 'Monte Leña'),
  ('Córdoba', 'Monte Maíz'),
  ('Córdoba', 'Monte Ralo'),
  ('Córdoba', 'Montecristo'),
  ('Córdoba', 'Morrison'),
  ('Córdoba', 'Morteros'),
  ('Córdoba', 'Nicolás Bruzzone'),
  ('Córdoba', 'Noetinger'),
  ('Córdoba', 'Nono'),
  ('Córdoba', 'Obispo Trejo'),
  ('Córdoba', 'Olaeta'),
  ('Córdoba', 'Oliva'),
  ('Córdoba', 'Olivares de San Nicolás'),
  ('Córdoba', 'Onagoity'),
  ('Córdoba', 'Oncativo'),
  ('Córdoba', 'Ordóñez'),
  ('Córdoba', 'Pacheco de Melo'),
  ('Córdoba', 'Pampayasta Norte'),
  ('Córdoba', 'Pampayasta Sud'),
  ('Córdoba', 'Panaholma'),
  ('Córdoba', 'Parque Calmayo'),
  ('Córdoba', 'Pascanas'),
  ('Córdoba', 'Pasco'),
  ('Córdoba', 'Paso del Durazno'),
  ('Córdoba', 'Paso Viejo'),
  ('Córdoba', 'Pilar'),
  ('Córdoba', 'Pincén'),
  ('Córdoba', 'Piquillín'),
  ('Córdoba', 'Plaza de Mercedes'),
  ('Córdoba', 'Plaza Luxardo'),
  ('Córdoba', 'Porteña'),
  ('Córdoba', 'Potrero de Garay'),
  ('Córdoba', 'Pozo del Molle'),
  ('Córdoba', 'Pozo Nuevo'),
  ('Córdoba', 'Pueblo Italiano'),
  ('Córdoba', 'Puesto de Castro'),
  ('Córdoba', 'Punta del Agua'),
  ('Córdoba', 'Quebracho Herrado'),
  ('Córdoba', 'Quilino'),
  ('Córdoba', 'Rafael García'),
  ('Córdoba', 'Ranqueles'),
  ('Córdoba', 'Rayo Cortado'),
  ('Córdoba', 'Reducción'),
  ('Córdoba', 'Rincón'),
  ('Córdoba', 'Río Bamba'),
  ('Córdoba', 'Río Ceballos'),
  ('Córdoba', 'Río Cuarto'),
  ('Córdoba', 'Río de los Sauces'),
  ('Córdoba', 'Río Primero'),
  ('Córdoba', 'Río Segundo'),
  ('Córdoba', 'Río Tercero'),
  ('Córdoba', 'Rosales'),
  ('Córdoba', 'Rosario del Saladillo'),
  ('Córdoba', 'Sacanta'),
  ('Córdoba', 'Sagrada Familia'),
  ('Córdoba', 'Saira'),
  ('Córdoba', 'Saladillo'),
  ('Córdoba', 'Saldán'),
  ('Córdoba', 'Salsacate'),
  ('Córdoba', 'Salsipuedes'),
  ('Córdoba', 'Sampacho'),
  ('Córdoba', 'San Agustín'),
  ('Córdoba', 'San Antonio de Arredondo'),
  ('Córdoba', 'San Antonio de Litín'),
  ('Córdoba', 'San Basilio'),
  ('Córdoba', 'San Carlos Minas'),
  ('Córdoba', 'San Clemente'),
  ('Córdoba', 'San Esteban'),
  ('Córdoba', 'San Francisco'),
  ('Córdoba', 'San Francisco del Chañar'),
  ('Córdoba', 'San Gerónimo'),
  ('Córdoba', 'San Ignacio'),
  ('Córdoba', 'San Javier y Yacanto'),
  ('Córdoba', 'San Joaquín'),
  ('Córdoba', 'San José'),
  ('Córdoba', 'San José de la Dormida'),
  ('Córdoba', 'San José de las Salinas'),
  ('Córdoba', 'San Lorenzo'),
  ('Córdoba', 'San Marcos Sierra'),
  ('Córdoba', 'San Marcos Sud'),
  ('Córdoba', 'San Pedro'),
  ('Córdoba', 'San Pedro Norte'),
  ('Córdoba', 'San Roque'),
  ('Córdoba', 'San Vicente'),
  ('Córdoba', 'Santa Catalina Holmberg'),
  ('Córdoba', 'Santa Elena'),
  ('Córdoba', 'Santa Eufemia'),
  ('Córdoba', 'Santa María de Punilla'),
  ('Córdoba', 'Santa Rosa de Calamuchita'),
  ('Córdoba', 'Santiago Temple'),
  ('Córdoba', 'Sarmiento'),
  ('Córdoba', 'Saturnino María Laspiur'),
  ('Córdoba', 'Sauce Arriba'),
  ('Córdoba', 'Sebastián Elcano'),
  ('Córdoba', 'Seeber'),
  ('Córdoba', 'Segunda Usina'),
  ('Córdoba', 'Serrano'),
  ('Córdoba', 'Serrezuela'),
  ('Córdoba', 'Silvio Pellico'),
  ('Córdoba', 'Simbolar'),
  ('Córdoba', 'Sinsacate'),
  ('Córdoba', 'Suco'),
  ('Córdoba', 'Tala Cañada'),
  ('Córdoba', 'Tala Huasi'),
  ('Córdoba', 'Talaini'),
  ('Córdoba', 'Tancacha'),
  ('Córdoba', 'Tanti'),
  ('Córdoba', 'Ticino'),
  ('Córdoba', 'Tinoco'),
  ('Córdoba', 'Tío Pujio'),
  ('Córdoba', 'Toledo'),
  ('Córdoba', 'Toro Pujio'),
  ('Córdoba', 'Tosno'),
  ('Córdoba', 'Tosquita'),
  ('Córdoba', 'Tránsito'),
  ('Córdoba', 'Tuclame'),
  ('Córdoba', 'Ucacha'),
  ('Córdoba', 'Unquillo'),
  ('Córdoba', 'Valle de Anisacate'),
  ('Córdoba', 'Valle Hermoso'),
  ('Córdoba', 'Viamonte'),
  ('Córdoba', 'Vicuña Mackenna'),
  ('Córdoba', 'Villa Allende'),
  ('Córdoba', 'Villa Amancay'),
  ('Córdoba', 'Villa Ascasubi'),
  ('Córdoba', 'Villa Candelaria Norte'),
  ('Córdoba', 'Villa Carlos Paz'),
  ('Córdoba', 'Villa Cerro Azul'),
  ('Córdoba', 'Villa Ciudad de América'),
  ('Córdoba', 'Villa Ciudad Parque Los Reartes'),
  ('Córdoba', 'Villa Concepción del Tío'),
  ('Córdoba', 'Villa Cura Brochero'),
  ('Córdoba', 'Villa de las Rosas'),
  ('Córdoba', 'Villa de María'),
  ('Córdoba', 'Villa de Pocho'),
  ('Córdoba', 'Villa de Soto'),
  ('Córdoba', 'Villa del Dique'),
  ('Córdoba', 'Villa del Prado'),
  ('Córdoba', 'Villa del Rosario'),
  ('Córdoba', 'Villa del Totoral'),
  ('Córdoba', 'Villa Dolores'),
  ('Córdoba', 'Villa El Chacay'),
  ('Córdoba', 'Villa Elisa'),
  ('Córdoba', 'Villa Fontana'),
  ('Córdoba', 'Villa General Belgrano'),
  ('Córdoba', 'Villa Giardino'),
  ('Córdoba', 'Villa Gutiérrez'),
  ('Córdoba', 'Villa Huidobro'),
  ('Córdoba', 'Villa La Bolsa'),
  ('Córdoba', 'Villa Los Aromos'),
  ('Córdoba', 'Villa Los Patos'),
  ('Córdoba', 'Villa María'),
  ('Córdoba', 'Villa Nueva'),
  ('Córdoba', 'Villa Parque Santa Ana'),
  ('Córdoba', 'Villa Parque Síquiman'),
  ('Córdoba', 'Villa Quillinzo'),
  ('Córdoba', 'Villa Río Icho Cruz'),
  ('Córdoba', 'Villa Rossi'),
  ('Córdoba', 'Villa Rumipal'),
  ('Córdoba', 'Villa San Esteban'),
  ('Córdoba', 'Villa San Isidro'),
  ('Córdoba', 'Villa Santa Cruz del Lago'),
  ('Córdoba', 'Villa Santa Rosa'),
  ('Córdoba', 'Villa Sarmiento'),
  ('Córdoba', 'Villa Tulumba'),
  ('Córdoba', 'Villa Valeria'),
  ('Córdoba', 'Villa Yacanto'),
  ('Córdoba', 'Washington'),
  ('Córdoba', 'Wenceslao Escalante'),
  ('Corrientes', '9 de Julio'),
  ('Corrientes', 'Alvear'),
  ('Corrientes', 'Bella Vista'),
  ('Corrientes', 'Bonpland'),
  ('Corrientes', 'Caá Catí'),
  ('Corrientes', 'Carolina'),
  ('Corrientes', 'Cazadores Correntinos'),
  ('Corrientes', 'Cecilio Echavarría'),
  ('Corrientes', 'Chavarría'),
  ('Corrientes', 'Colonia Carlos Pellegrini'),
  ('Corrientes', 'Colonia Libertad'),
  ('Corrientes', 'Colonia Liebig'),
  ('Corrientes', 'Colonia Pando'),
  ('Corrientes', 'Colonia Santa Rosa'),
  ('Corrientes', 'Concepción del Yaguareté Corá'),
  ('Corrientes', 'Corrientes'),
  ('Corrientes', 'Cruz de los Milagros'),
  ('Corrientes', 'Curuzú Cuatiá'),
  ('Corrientes', 'El Sombrero'),
  ('Corrientes', 'Empedrado'),
  ('Corrientes', 'Esquina'),
  ('Corrientes', 'Estación Torrent'),
  ('Corrientes', 'Felipe Yofré'),
  ('Corrientes', 'Garaví'),
  ('Corrientes', 'Garruchos'),
  ('Corrientes', 'Gobernador Martínez'),
  ('Corrientes', 'Gobernador Virasoro'),
  ('Corrientes', 'Goya'),
  ('Corrientes', 'Guaviraví'),
  ('Corrientes', 'Herlitzka'),
  ('Corrientes', 'Itá Ibaté'),
  ('Corrientes', 'Itatí'),
  ('Corrientes', 'Ituzaingó'),
  ('Corrientes', 'Juan Pujol'),
  ('Corrientes', 'La Cruz'),
  ('Corrientes', 'Lavalle'),
  ('Corrientes', 'Lomas de Vallejos'),
  ('Corrientes', 'Loreto'),
  ('Corrientes', 'Mariano I. Loza'),
  ('Corrientes', 'Mburucuyá'),
  ('Corrientes', 'Mercedes'),
  ('Corrientes', 'Mocoretá'),
  ('Corrientes', 'Monte Caseros'),
  ('Corrientes', 'Pago de los Deseos'),
  ('Corrientes', 'Palmar Grande'),
  ('Corrientes', 'Parada Pucheta'),
  ('Corrientes', 'Paso de la Patria'),
  ('Corrientes', 'Paso de los Libres'),
  ('Corrientes', 'Pedro R. Fernández'),
  ('Corrientes', 'Perugorría'),
  ('Corrientes', 'Pueblo Libertador'),
  ('Corrientes', 'Ramada Paso'),
  ('Corrientes', 'Riachuelo'),
  ('Corrientes', 'Saladas'),
  ('Corrientes', 'San Antonio de Itatí'),
  ('Corrientes', 'San Antonio Isla Apipé Grande'),
  ('Corrientes', 'San Carlos'),
  ('Corrientes', 'San Cosme'),
  ('Corrientes', 'San Isidro'),
  ('Corrientes', 'San Lorenzo'),
  ('Corrientes', 'San Luis del Palmar'),
  ('Corrientes', 'San Miguel'),
  ('Corrientes', 'San Roque'),
  ('Corrientes', 'Santa Ana de los Guácaras'),
  ('Corrientes', 'Santa Lucía'),
  ('Corrientes', 'Santo Tomé'),
  ('Corrientes', 'Sauce'),
  ('Corrientes', 'Tabay'),
  ('Corrientes', 'Tapebicuá'),
  ('Corrientes', 'Tatacuá'),
  ('Corrientes', 'Tres de Abril'),
  ('Corrientes', 'Villa Olivari'),
  ('Corrientes', 'Yapeyú'),
  ('Corrientes', 'Yatay Ti Calle'),
  ('Entre Ríos', '1º de Mayo'),
  ('Entre Ríos', 'Alcaraz'),
  ('Entre Ríos', 'Alcaraz Norte'),
  ('Entre Ríos', 'Alcaraz Sur'),
  ('Entre Ríos', 'Aldea Asunción'),
  ('Entre Ríos', 'Aldea Brasilera'),
  ('Entre Ríos', 'Aldea Eigenfeld'),
  ('Entre Ríos', 'Aldea Grapschental'),
  ('Entre Ríos', 'Aldea Protestante'),
  ('Entre Ríos', 'Aldea Salto'),
  ('Entre Ríos', 'Aldea San Antonio'),
  ('Entre Ríos', 'Aldea San Juan'),
  ('Entre Ríos', 'Aldea San Miguel'),
  ('Entre Ríos', 'Aldea San Rafael'),
  ('Entre Ríos', 'Aldea Santa María'),
  ('Entre Ríos', 'Aldea Santa Rosa'),
  ('Entre Ríos', 'Aldea Spatzenkutter'),
  ('Entre Ríos', 'Aldea Valle María'),
  ('Entre Ríos', 'Altamirano Sur'),
  ('Entre Ríos', 'Antelo'),
  ('Entre Ríos', 'Antonio Tomás'),
  ('Entre Ríos', 'Arroyo Barú'),
  ('Entre Ríos', 'Arroyo Burgos'),
  ('Entre Ríos', 'Arroyo Cle'),
  ('Entre Ríos', 'Arroyo Corralito'),
  ('Entre Ríos', 'Arroyo del Medio'),
  ('Entre Ríos', 'Arroyo Gená'),
  ('Entre Ríos', 'Arroyo Las Tunas'),
  ('Entre Ríos', 'Arroyo Maturrango'),
  ('Entre Ríos', 'Arroyo Palo Seco'),
  ('Entre Ríos', 'Banderas'),
  ('Entre Ríos', 'Basavilbaso'),
  ('Entre Ríos', 'Betbeder'),
  ('Entre Ríos', 'Bovril'),
  ('Entre Ríos', 'Caseros'),
  ('Entre Ríos', 'Ceibas'),
  ('Entre Ríos', 'Cerrito'),
  ('Entre Ríos', 'Chajarí'),
  ('Entre Ríos', 'Chilcas'),
  ('Entre Ríos', 'Clodomiro Ledesma'),
  ('Entre Ríos', 'Colón'),
  ('Entre Ríos', 'Colonia Adivino'),
  ('Entre Ríos', 'Colonia Alemana'),
  ('Entre Ríos', 'Colonia Avellaneda'),
  ('Entre Ríos', 'Colonia Avigdor'),
  ('Entre Ríos', 'Colonia Ayuí'),
  ('Entre Ríos', 'Colonia Baylina'),
  ('Entre Ríos', 'Colonia Carrasco'),
  ('Entre Ríos', 'Colonia Celina'),
  ('Entre Ríos', 'Colonia Crespo'),
  ('Entre Ríos', 'Colonia Elía'),
  ('Entre Ríos', 'Colonia Ensayo'),
  ('Entre Ríos', 'Colonia La Argentina'),
  ('Entre Ríos', 'Colonia Merou'),
  ('Entre Ríos', 'Colonia Oficial N° 13'),
  ('Entre Ríos', 'Colonia Oficial Nº 3 y 14'),
  ('Entre Ríos', 'Colonia Oficial Nº 5'),
  ('Entre Ríos', 'Colonia San Anselmo y Aledañas'),
  ('Entre Ríos', 'Colonia Santa María y Las Margaritas'),
  ('Entre Ríos', 'Colonia Tunas'),
  ('Entre Ríos', 'Colonia Viraró'),
  ('Entre Ríos', 'Comuna Tala'),
  ('Entre Ríos', 'Concepción del Uruguay'),
  ('Entre Ríos', 'Concordia'),
  ('Entre Ríos', 'Conscripto Bernardi'),
  ('Entre Ríos', 'Costa Grande'),
  ('Entre Ríos', 'Costa San Antonio'),
  ('Entre Ríos', 'Costa Uruguay Norte'),
  ('Entre Ríos', 'Costa Uruguay Sur'),
  ('Entre Ríos', 'Crespo'),
  ('Entre Ríos', 'Crucesitas Octava'),
  ('Entre Ríos', 'Crucesitas Séptima'),
  ('Entre Ríos', 'Crucesitas Tercera'),
  ('Entre Ríos', 'Cuchilla Redonda'),
  ('Entre Ríos', 'Diamante'),
  ('Entre Ríos', 'Distrito Chañar'),
  ('Entre Ríos', 'Distrito Chiqueros'),
  ('Entre Ríos', 'Distrito Cuarto'),
  ('Entre Ríos', 'Distrito Diego López'),
  ('Entre Ríos', 'Distrito Pajonal'),
  ('Entre Ríos', 'Distrito Primero'),
  ('Entre Ríos', 'Distrito Quinto'),
  ('Entre Ríos', 'Distrito Sauce'),
  ('Entre Ríos', 'Distrito Sexto'),
  ('Entre Ríos', 'Distrito Tala'),
  ('Entre Ríos', 'Distrito Talitas'),
  ('Entre Ríos', 'Don Cristóbal I'),
  ('Entre Ríos', 'Don Cristóbal II'),
  ('Entre Ríos', 'Durazno'),
  ('Entre Ríos', 'El Cimarrón'),
  ('Entre Ríos', 'El Gramiyal'),
  ('Entre Ríos', 'El Palenque'),
  ('Entre Ríos', 'El Pingo'),
  ('Entre Ríos', 'El Quebracho'),
  ('Entre Ríos', 'El Redomón'),
  ('Entre Ríos', 'El Solar'),
  ('Entre Ríos', 'Enrique Carbó'),
  ('Entre Ríos', 'Espinillo Norte'),
  ('Entre Ríos', 'Estación Camps'),
  ('Entre Ríos', 'Estación Escriña'),
  ('Entre Ríos', 'Estación Lazo'),
  ('Entre Ríos', 'Estación Parera'),
  ('Entre Ríos', 'Estación Raíces'),
  ('Entre Ríos', 'Estación Sosa'),
  ('Entre Ríos', 'Estación Yeruá'),
  ('Entre Ríos', 'Estación Yuquerí'),
  ('Entre Ríos', 'Estancia Grande'),
  ('Entre Ríos', 'Estaquitas'),
  ('Entre Ríos', 'Febre'),
  ('Entre Ríos', 'Federación'),
  ('Entre Ríos', 'Federal'),
  ('Entre Ríos', 'General Almada'),
  ('Entre Ríos', 'General Alvear'),
  ('Entre Ríos', 'General Campos'),
  ('Entre Ríos', 'General Galarza'),
  ('Entre Ríos', 'General Ramírez'),
  ('Entre Ríos', 'General Roca'),
  ('Entre Ríos', 'Gilbert'),
  ('Entre Ríos', 'Gobernador Echagüe'),
  ('Entre Ríos', 'Gobernador Etchevehere'),
  ('Entre Ríos', 'Gobernador Mansilla'),
  ('Entre Ríos', 'Gobernador Racedo'),
  ('Entre Ríos', 'Gobernador Sola'),
  ('Entre Ríos', 'González Calderón'),
  ('Entre Ríos', 'Gualeguay'),
  ('Entre Ríos', 'Gualeguaycito'),
  ('Entre Ríos', 'Guardamonte'),
  ('Entre Ríos', 'Hambis'),
  ('Entre Ríos', 'Hasenkamp'),
  ('Entre Ríos', 'Hernandarias'),
  ('Entre Ríos', 'Herrera'),
  ('Entre Ríos', 'Hinojal'),
  ('Entre Ríos', 'Hocker'),
  ('Entre Ríos', 'Ibicuy'),
  ('Entre Ríos', 'Ingeniero Sajaroff'),
  ('Entre Ríos', 'Irazusta'),
  ('Entre Ríos', 'Isletas'),
  ('Entre Ríos', 'Jubileo'),
  ('Entre Ríos', 'Justo José de Urquiza'),
  ('Entre Ríos', 'La Clarita'),
  ('Entre Ríos', 'La Criolla'),
  ('Entre Ríos', 'La Esmeralda'),
  ('Entre Ríos', 'La Florida'),
  ('Entre Ríos', 'La Fraternidad y Santa Juana'),
  ('Entre Ríos', 'La Hierra'),
  ('Entre Ríos', 'La Ollita'),
  ('Entre Ríos', 'La Paz'),
  ('Entre Ríos', 'La Picada'),
  ('Entre Ríos', 'La Providencia'),
  ('Entre Ríos', 'La Verbena'),
  ('Entre Ríos', 'Laguna Benítez'),
  ('Entre Ríos', 'Laguna del Pescado'),
  ('Entre Ríos', 'Larroque'),
  ('Entre Ríos', 'Las Cuevas'),
  ('Entre Ríos', 'Las Garzas'),
  ('Entre Ríos', 'Las Guachas'),
  ('Entre Ríos', 'Las Mercedes'),
  ('Entre Ríos', 'Las Moscas'),
  ('Entre Ríos', 'Las Mulitas'),
  ('Entre Ríos', 'Las Toscas'),
  ('Entre Ríos', 'Laurencena'),
  ('Entre Ríos', 'Líbaros'),
  ('Entre Ríos', 'Loma Limpia'),
  ('Entre Ríos', 'Los Charrúas'),
  ('Entre Ríos', 'Los Conquistadores'),
  ('Entre Ríos', 'Lucas González'),
  ('Entre Ríos', 'Lucas Norte'),
  ('Entre Ríos', 'Lucas Sur Primero'),
  ('Entre Ríos', 'Lucas Sur Segundo'),
  ('Entre Ríos', 'Maciá'),
  ('Entre Ríos', 'María Grande'),
  ('Entre Ríos', 'María Grande 2º'),
  ('Entre Ríos', 'Maria Luisa'),
  ('Entre Ríos', 'Médanos'),
  ('Entre Ríos', 'Mojones Norte'),
  ('Entre Ríos', 'Mojones Sur'),
  ('Entre Ríos', 'Molino Doll'),
  ('Entre Ríos', 'Monte Redondo'),
  ('Entre Ríos', 'Montoya'),
  ('Entre Ríos', 'Mulas Grandes'),
  ('Entre Ríos', 'Nogoyá'),
  ('Entre Ríos', 'Nueva Escocia'),
  ('Entre Ríos', 'Nueva Vizcaya'),
  ('Entre Ríos', 'Ñancay'),
  ('Entre Ríos', 'Ombú'),
  ('Entre Ríos', 'Oro Verde'),
  ('Entre Ríos', 'Paraje Guayaquil'),
  ('Entre Ríos', 'Paraje Las Tunas'),
  ('Entre Ríos', 'Paraje Los Algarrobos'),
  ('Entre Ríos', 'Paraná'),
  ('Entre Ríos', 'Paso de la Arena'),
  ('Entre Ríos', 'Paso de La Laguna'),
  ('Entre Ríos', 'Paso de las Piedras'),
  ('Entre Ríos', 'Paso Duarte'),
  ('Entre Ríos', 'Pastor Britos'),
  ('Entre Ríos', 'Pedernal'),
  ('Entre Ríos', 'Perdices'),
  ('Entre Ríos', 'Picada Berón'),
  ('Entre Ríos', 'Piedras Blancas'),
  ('Entre Ríos', 'Pronunciamiento'),
  ('Entre Ríos', 'Pueblo Brugo'),
  ('Entre Ríos', 'Pueblo Cazes'),
  ('Entre Ríos', 'Pueblo General Belgrano'),
  ('Entre Ríos', 'Pueblo Liebig'),
  ('Entre Ríos', 'Puerto Algarrobo'),
  ('Entre Ríos', 'Puerto Curtiembre'),
  ('Entre Ríos', 'Puerto Yeruá'),
  ('Entre Ríos', 'Punta del Monte'),
  ('Entre Ríos', 'Quebracho'),
  ('Entre Ríos', 'Raíces Oeste'),
  ('Entre Ríos', 'Rincón de Nogoyá'),
  ('Entre Ríos', 'Rincón del Cinto'),
  ('Entre Ríos', 'Rincón del Doll'),
  ('Entre Ríos', 'Rincón del Gato'),
  ('Entre Ríos', 'Rocamora'),
  ('Entre Ríos', 'Rosario del Tala'),
  ('Entre Ríos', 'San Benito'),
  ('Entre Ríos', 'San Cipriano'),
  ('Entre Ríos', 'San Ernesto'),
  ('Entre Ríos', 'San Gustavo'),
  ('Entre Ríos', 'San Jaime de la Frontera'),
  ('Entre Ríos', 'San José'),
  ('Entre Ríos', 'San José de Feliciano'),
  ('Entre Ríos', 'San José de Gualeguaychú'),
  ('Entre Ríos', 'San Justo'),
  ('Entre Ríos', 'San Marcial'),
  ('Entre Ríos', 'San Miguel'),
  ('Entre Ríos', 'San Pedro'),
  ('Entre Ríos', 'San Ramírez'),
  ('Entre Ríos', 'San Ramón'),
  ('Entre Ríos', 'San Roque'),
  ('Entre Ríos', 'San Salvador'),
  ('Entre Ríos', 'San Víctor'),
  ('Entre Ríos', 'Santa Ana'),
  ('Entre Ríos', 'Santa Anita'),
  ('Entre Ríos', 'Santa Elena'),
  ('Entre Ríos', 'Santa Lucía'),
  ('Entre Ríos', 'Santa Luisa'),
  ('Entre Ríos', 'Sauce de Luna'),
  ('Entre Ríos', 'Sauce Montrull'),
  ('Entre Ríos', 'Sauce Pinto'),
  ('Entre Ríos', 'Sauce Sur'),
  ('Entre Ríos', 'Saucecito'),
  ('Entre Ríos', 'Seguí'),
  ('Entre Ríos', 'Sir Leonard'),
  ('Entre Ríos', 'Tabossi'),
  ('Entre Ríos', 'Tezanos Pinto'),
  ('Entre Ríos', 'Ubajay'),
  ('Entre Ríos', 'Urdinarrain'),
  ('Entre Ríos', 'Viale'),
  ('Entre Ríos', 'Victoria'),
  ('Entre Ríos', 'Villa Aranguren'),
  ('Entre Ríos', 'Villa Clara'),
  ('Entre Ríos', 'Villa del Rosario'),
  ('Entre Ríos', 'Villa Domínguez'),
  ('Entre Ríos', 'Villa Elisa'),
  ('Entre Ríos', 'Villa Fontana'),
  ('Entre Ríos', 'Villa Libertador San Martín'),
  ('Entre Ríos', 'Villa Mantero'),
  ('Entre Ríos', 'Villa Paranacito'),
  ('Entre Ríos', 'Villa Sabá Z. Hernández'),
  ('Entre Ríos', 'Villa Urquiza'),
  ('Entre Ríos', 'Villaguay'),
  ('Entre Ríos', 'Walter Moss'),
  ('Entre Ríos', 'XX de Septiembre'),
  ('Entre Ríos', 'Yacaré'),
  ('Entre Ríos', 'Yeso Oeste'),
  ('Formosa', 'Buena Vista'),
  ('Formosa', 'Clorinda'),
  ('Formosa', 'Colonia Pastoril'),
  ('Formosa', 'Comandante Fontana'),
  ('Formosa', 'El Chorro'),
  ('Formosa', 'El Colorado'),
  ('Formosa', 'El Espinillo'),
  ('Formosa', 'Estanislao del Campo'),
  ('Formosa', 'Formosa'),
  ('Formosa', 'Fortín Lugones'),
  ('Formosa', 'General Lucio Victorio Mansilla'),
  ('Formosa', 'General Manuel Belgrano'),
  ('Formosa', 'Gran Guardia'),
  ('Formosa', 'Herradura'),
  ('Formosa', 'Ibarreta'),
  ('Formosa', 'Ingeniero Guillermo Nicasio Juárez'),
  ('Formosa', 'Laguna Blanca'),
  ('Formosa', 'Laguna Naick Neck'),
  ('Formosa', 'Laguna Yema'),
  ('Formosa', 'Las Lomitas'),
  ('Formosa', 'Los Chiriguanos'),
  ('Formosa', 'Mayor Villafañe'),
  ('Formosa', 'Misión San Francisco de Laishi'),
  ('Formosa', 'Misión Tacaaglé'),
  ('Formosa', 'Palo Santo'),
  ('Formosa', 'Pirané'),
  ('Formosa', 'Portón Negro'),
  ('Formosa', 'Pozo del Tigre'),
  ('Formosa', 'Riacho He He'),
  ('Formosa', 'San Hilario'),
  ('Formosa', 'San Martín Dos'),
  ('Formosa', 'Siete Palmas'),
  ('Formosa', 'Subteniente Perín'),
  ('Formosa', 'Tres Lagunas'),
  ('Formosa', 'Villa Dos Trece'),
  ('Formosa', 'Villa Escolar'),
  ('Formosa', 'Villa General Güemes'),
  ('Jujuy', 'Abdón Castro Tolay'),
  ('Jujuy', 'Abra Pampa'),
  ('Jujuy', 'Abralaite'),
  ('Jujuy', 'Aguas Calientes'),
  ('Jujuy', 'Arrayanal'),
  ('Jujuy', 'Barrios'),
  ('Jujuy', 'Caimancito'),
  ('Jujuy', 'Calilegua'),
  ('Jujuy', 'Cangrejillos'),
  ('Jujuy', 'Caspalá'),
  ('Jujuy', 'Catua'),
  ('Jujuy', 'Cieneguillas'),
  ('Jujuy', 'Coranzuli'),
  ('Jujuy', 'Cusi Cusi'),
  ('Jujuy', 'El Aguilar'),
  ('Jujuy', 'El Carmen'),
  ('Jujuy', 'El Cóndor'),
  ('Jujuy', 'El Fuerte'),
  ('Jujuy', 'El Moreno'),
  ('Jujuy', 'El Piquete'),
  ('Jujuy', 'El Talar'),
  ('Jujuy', 'Fraile Pintado'),
  ('Jujuy', 'Hipólito Yrigoyen'),
  ('Jujuy', 'Huacalera'),
  ('Jujuy', 'Humahuaca'),
  ('Jujuy', 'La Esperanza'),
  ('Jujuy', 'La Mendieta'),
  ('Jujuy', 'La Quiaca'),
  ('Jujuy', 'Libertador General San Martín'),
  ('Jujuy', 'Maimará'),
  ('Jujuy', 'Mina Pirquitas'),
  ('Jujuy', 'Monterrico'),
  ('Jujuy', 'Palca de Aparzo'),
  ('Jujuy', 'Palma Sola'),
  ('Jujuy', 'Palpalá'),
  ('Jujuy', 'Pampa Blanca'),
  ('Jujuy', 'Pampichuela'),
  ('Jujuy', 'Perico'),
  ('Jujuy', 'Puesto del Marquez'),
  ('Jujuy', 'Puesto Viejo'),
  ('Jujuy', 'Pumahuasi'),
  ('Jujuy', 'Purmamarca'),
  ('Jujuy', 'Rinconada'),
  ('Jujuy', 'Rodeito'),
  ('Jujuy', 'Rosario de Río Grande'),
  ('Jujuy', 'San Antonio'),
  ('Jujuy', 'San Francisco'),
  ('Jujuy', 'San Pedro de Jujuy'),
  ('Jujuy', 'San Salvador de Jujuy'),
  ('Jujuy', 'Santa Ana'),
  ('Jujuy', 'Santa Catalina'),
  ('Jujuy', 'Santa Clara'),
  ('Jujuy', 'Susques'),
  ('Jujuy', 'Tilcara'),
  ('Jujuy', 'Tres Cruces'),
  ('Jujuy', 'Tumbaya'),
  ('Jujuy', 'Uquia'),
  ('Jujuy', 'Valle Grande'),
  ('Jujuy', 'Vinalito'),
  ('Jujuy', 'Volcán'),
  ('Jujuy', 'Yala'),
  ('Jujuy', 'Yavi'),
  ('Jujuy', 'Yuto'),
  ('La Pampa', 'Abramo'),
  ('La Pampa', 'Adolfo Van Praet'),
  ('La Pampa', 'Agustoni'),
  ('La Pampa', 'Algarrobo del Águila'),
  ('La Pampa', 'Alpachiri'),
  ('La Pampa', 'Alta Italia'),
  ('La Pampa', 'Anguil'),
  ('La Pampa', 'Arata'),
  ('La Pampa', 'Ataliva Roca'),
  ('La Pampa', 'Bernardo Larroudé'),
  ('La Pampa', 'Bernasconi'),
  ('La Pampa', 'Caleufú'),
  ('La Pampa', 'Carro Quemado'),
  ('La Pampa', 'Casa de Piedra'),
  ('La Pampa', 'Catriló'),
  ('La Pampa', 'Ceballos'),
  ('La Pampa', 'Chacharramendi'),
  ('La Pampa', 'Colonia 25 de Mayo'),
  ('La Pampa', 'Colonia Barón'),
  ('La Pampa', 'Colonia Santa María'),
  ('La Pampa', 'Colonia Santa Teresa'),
  ('La Pampa', 'Conhelo'),
  ('La Pampa', 'Coronel Hilario Lagos'),
  ('La Pampa', 'Cuchillo Co'),
  ('La Pampa', 'Doblas'),
  ('La Pampa', 'Dorila'),
  ('La Pampa', 'Eduardo Castex'),
  ('La Pampa', 'Embajador Martini'),
  ('La Pampa', 'Falucho'),
  ('La Pampa', 'General Acha'),
  ('La Pampa', 'General Campos'),
  ('La Pampa', 'General Pico'),
  ('La Pampa', 'General San Martín'),
  ('La Pampa', 'Gobernador Duval'),
  ('La Pampa', 'Guatraché'),
  ('La Pampa', 'Ingeniero Luiggi'),
  ('La Pampa', 'Intendente Alvear'),
  ('La Pampa', 'Jacinto Aráuz'),
  ('La Pampa', 'La Adela'),
  ('La Pampa', 'La Humada'),
  ('La Pampa', 'La Maruja'),
  ('La Pampa', 'La Reforma'),
  ('La Pampa', 'Limay Mahuida'),
  ('La Pampa', 'Lonquimay'),
  ('La Pampa', 'Loventué'),
  ('La Pampa', 'Luan Toro'),
  ('La Pampa', 'Macachín'),
  ('La Pampa', 'Maisonave'),
  ('La Pampa', 'Mauricio Mayer'),
  ('La Pampa', 'Metileo'),
  ('La Pampa', 'Miguel Cané'),
  ('La Pampa', 'Miguel Riglos'),
  ('La Pampa', 'Monte Nievas'),
  ('La Pampa', 'Parera'),
  ('La Pampa', 'Perú'),
  ('La Pampa', 'Pichi Huinca'),
  ('La Pampa', 'Puelches'),
  ('La Pampa', 'Puelén'),
  ('La Pampa', 'Quehué'),
  ('La Pampa', 'Quemú Quemú'),
  ('La Pampa', 'Quetrequén'),
  ('La Pampa', 'Rancul'),
  ('La Pampa', 'Realicó'),
  ('La Pampa', 'Relmo'),
  ('La Pampa', 'Rolón'),
  ('La Pampa', 'Rucanelo'),
  ('La Pampa', 'Santa Isabel'),
  ('La Pampa', 'Santa Rosa'),
  ('La Pampa', 'Sarah'),
  ('La Pampa', 'Speluzzi'),
  ('La Pampa', 'Telén'),
  ('La Pampa', 'Toay'),
  ('La Pampa', 'Tomás M. Anchorena'),
  ('La Pampa', 'Trenel'),
  ('La Pampa', 'Unanué'),
  ('La Pampa', 'Uriburu'),
  ('La Pampa', 'Vértiz'),
  ('La Pampa', 'Victorica'),
  ('La Pampa', 'Villa Mirasol'),
  ('La Pampa', 'Winifreda'),
  ('La Rioja', 'Ángel Vicente Peñaloza'),
  ('La Rioja', 'Arauco'),
  ('La Rioja', 'Castro Barros'),
  ('La Rioja', 'Chamical'),
  ('La Rioja', 'Chilecito'),
  ('La Rioja', 'Famatina'),
  ('La Rioja', 'General Belgrano'),
  ('La Rioja', 'General Felipe Varela'),
  ('La Rioja', 'General Juan Facundo Quiroga'),
  ('La Rioja', 'General Lamadrid'),
  ('La Rioja', 'General Ortiz de Ocampo'),
  ('La Rioja', 'General San Martín'),
  ('La Rioja', 'Independencia'),
  ('La Rioja', 'La Rioja'),
  ('La Rioja', 'Rosario Vera Peñaloza'),
  ('La Rioja', 'San Blas de Los Sauces'),
  ('La Rioja', 'Sanagasta'),
  ('La Rioja', 'Vinchina'),
  ('Mendoza', 'General Alvear'),
  ('Mendoza', 'Godoy Cruz'),
  ('Mendoza', 'Guaymallén'),
  ('Mendoza', 'Junín'),
  ('Mendoza', 'La Paz'),
  ('Mendoza', 'Las Heras'),
  ('Mendoza', 'Lavalle'),
  ('Mendoza', 'Luján de Cuyo'),
  ('Mendoza', 'Maipú'),
  ('Mendoza', 'Malargüe'),
  ('Mendoza', 'Mendoza'),
  ('Mendoza', 'Rivadavia'),
  ('Mendoza', 'San Carlos'),
  ('Mendoza', 'San Martín'),
  ('Mendoza', 'San Rafael'),
  ('Mendoza', 'Santa Rosa'),
  ('Mendoza', 'Tunuyán'),
  ('Mendoza', 'Tupungato'),
  ('Misiones', '25 de Mayo'),
  ('Misiones', '9 de Julio'),
  ('Misiones', 'Alba Posse'),
  ('Misiones', 'Almafuerte'),
  ('Misiones', 'Apóstoles'),
  ('Misiones', 'Aristóbulo del Valle'),
  ('Misiones', 'Arroyo del Medio'),
  ('Misiones', 'Azara'),
  ('Misiones', 'Bernardo de Irigoyen'),
  ('Misiones', 'Bonpland'),
  ('Misiones', 'Caá Yarí'),
  ('Misiones', 'Campo Grande'),
  ('Misiones', 'Campo Ramón'),
  ('Misiones', 'Campo Viera'),
  ('Misiones', 'Candelaria'),
  ('Misiones', 'Capioví'),
  ('Misiones', 'Caraguatay'),
  ('Misiones', 'Cerro Azul'),
  ('Misiones', 'Cerro Corá'),
  ('Misiones', 'Colonia Alberdi'),
  ('Misiones', 'Colonia Aurora'),
  ('Misiones', 'Colonia Delicia'),
  ('Misiones', 'Colonia Polana'),
  ('Misiones', 'Colonia Victoria'),
  ('Misiones', 'Colonia Wanda'),
  ('Misiones', 'Comandante Andresito'),
  ('Misiones', 'Concepción de la Sierra'),
  ('Misiones', 'Corpus Christi'),
  ('Misiones', 'Dos Arroyos'),
  ('Misiones', 'Dos de Mayo'),
  ('Misiones', 'El Alcázar'),
  ('Misiones', 'El Soberbio'),
  ('Misiones', 'Eldorado'),
  ('Misiones', 'Fachinal'),
  ('Misiones', 'Florentino Ameghino'),
  ('Misiones', 'Garuhapé'),
  ('Misiones', 'Garupá'),
  ('Misiones', 'General Alvear'),
  ('Misiones', 'General Urquiza'),
  ('Misiones', 'Gobernador López'),
  ('Misiones', 'Gobernador Roca'),
  ('Misiones', 'Guaraní'),
  ('Misiones', 'Hipólito Yrigoyen'),
  ('Misiones', 'Itacaruaré'),
  ('Misiones', 'Jardín América'),
  ('Misiones', 'Leandro N. Alem'),
  ('Misiones', 'Libertad'),
  ('Misiones', 'Loreto'),
  ('Misiones', 'Los Helechos'),
  ('Misiones', 'Mártires'),
  ('Misiones', 'Mojón Grande'),
  ('Misiones', 'Montecarlo'),
  ('Misiones', 'Oberá'),
  ('Misiones', 'Olegario V. Andrade'),
  ('Misiones', 'Panambí'),
  ('Misiones', 'Posadas'),
  ('Misiones', 'Pozo Azul'),
  ('Misiones', 'Profundidad'),
  ('Misiones', 'Puerto Esperanza'),
  ('Misiones', 'Puerto Iguazú'),
  ('Misiones', 'Puerto Leoni'),
  ('Misiones', 'Puerto Piray'),
  ('Misiones', 'Puerto Rico'),
  ('Misiones', 'Ruiz de Montoya'),
  ('Misiones', 'San Antonio'),
  ('Misiones', 'San Ignacio'),
  ('Misiones', 'San Javier'),
  ('Misiones', 'San José'),
  ('Misiones', 'San Martín'),
  ('Misiones', 'San Pedro'),
  ('Misiones', 'San Vicente'),
  ('Misiones', 'Santa Ana'),
  ('Misiones', 'Santa María'),
  ('Misiones', 'Santiago de Liniers'),
  ('Misiones', 'Santo Pipó'),
  ('Misiones', 'Tres Capones'),
  ('Neuquén', 'Aguada San Roque'),
  ('Neuquén', 'Aluminé'),
  ('Neuquén', 'Andacollo'),
  ('Neuquén', 'Añelo'),
  ('Neuquén', 'Bajada del Agrio'),
  ('Neuquén', 'Barrancas'),
  ('Neuquén', 'Buta Ranquil'),
  ('Neuquén', 'Caviahue - Copahue'),
  ('Neuquén', 'Centenario'),
  ('Neuquén', 'Chorriaca'),
  ('Neuquén', 'Chos Malal'),
  ('Neuquén', 'Covunco Abajo'),
  ('Neuquén', 'Coyuco - Cochico'),
  ('Neuquén', 'Cutral Co'),
  ('Neuquén', 'El Cholar'),
  ('Neuquén', 'El Huecú'),
  ('Neuquén', 'El Sauce'),
  ('Neuquén', 'Guañacos'),
  ('Neuquén', 'Huinganco'),
  ('Neuquén', 'Junín de los Andes'),
  ('Neuquén', 'Las Coloradas'),
  ('Neuquén', 'Las Lajas'),
  ('Neuquén', 'Las Ovejas'),
  ('Neuquén', 'Loncopué'),
  ('Neuquén', 'Los Catutos'),
  ('Neuquén', 'Los Chihuidos'),
  ('Neuquén', 'Los Miches'),
  ('Neuquén', 'Manzano Amargo'),
  ('Neuquén', 'Mariano Moreno'),
  ('Neuquén', 'Neuquén'),
  ('Neuquén', 'Octavio Pico'),
  ('Neuquén', 'Paso Aguerre'),
  ('Neuquén', 'Picún Leufú'),
  ('Neuquén', 'Piedra del Águila'),
  ('Neuquén', 'Pilo Lil'),
  ('Neuquén', 'Plaza Huincul'),
  ('Neuquén', 'Plottier'),
  ('Neuquén', 'Quili Malal'),
  ('Neuquén', 'Ramón M. Castro'),
  ('Neuquén', 'Rincón de los Sauces'),
  ('Neuquén', 'San Martín de los Andes'),
  ('Neuquén', 'San Patricio del Chañar'),
  ('Neuquén', 'Santo Tomás'),
  ('Neuquén', 'Sauzal Bonito'),
  ('Neuquén', 'Senillosa'),
  ('Neuquén', 'Taquimilán'),
  ('Neuquén', 'Tricao Malal'),
  ('Neuquén', 'Varvarco - Invernada Vieja'),
  ('Neuquén', 'Villa Curi Leuvú'),
  ('Neuquén', 'Villa del Nahueve'),
  ('Neuquén', 'Villa El Chocón'),
  ('Neuquén', 'Villa La Angostura'),
  ('Neuquén', 'Villa Pehuenia'),
  ('Neuquén', 'Villa Puente Picún Leufú'),
  ('Neuquén', 'Villa Traful'),
  ('Neuquén', 'Vista Alegre'),
  ('Neuquén', 'Zapala'),
  ('Río Negro', 'Allen'),
  ('Río Negro', 'Campo Grande'),
  ('Río Negro', 'Catriel'),
  ('Río Negro', 'Cervantes'),
  ('Río Negro', 'Chichinales'),
  ('Río Negro', 'Chimpay'),
  ('Río Negro', 'Choele Choel'),
  ('Río Negro', 'Cinco Saltos'),
  ('Río Negro', 'Cipolletti'),
  ('Río Negro', 'Comallo'),
  ('Río Negro', 'Contralmirante Cordero'),
  ('Río Negro', 'Coronel Belisle'),
  ('Río Negro', 'Darwin'),
  ('Río Negro', 'Dina Huapi'),
  ('Río Negro', 'El Bolsón'),
  ('Río Negro', 'General Conesa'),
  ('Río Negro', 'General Enrique Godoy'),
  ('Río Negro', 'General Fernández Oro'),
  ('Río Negro', 'General Roca'),
  ('Río Negro', 'Guardia Mitre'),
  ('Río Negro', 'Ingeniero Huergo'),
  ('Río Negro', 'Ingeniero Jacobacci'),
  ('Río Negro', 'Lamarque'),
  ('Río Negro', 'Los Menucos'),
  ('Río Negro', 'Luis Beltrán'),
  ('Río Negro', 'Mainqué'),
  ('Río Negro', 'Maquinchao'),
  ('Río Negro', 'Ministro Ramos Mexía'),
  ('Río Negro', 'Ñorquinco'),
  ('Río Negro', 'Pilcaniyeu'),
  ('Río Negro', 'Pomona'),
  ('Río Negro', 'Río Colorado'),
  ('Río Negro', 'San Antonio Oeste'),
  ('Río Negro', 'San Carlos de Bariloche'),
  ('Río Negro', 'Sierra Colorada'),
  ('Río Negro', 'Sierra Grande'),
  ('Río Negro', 'Valcheta'),
  ('Río Negro', 'Viedma'),
  ('Río Negro', 'Villa Regina'),
  ('Salta', 'Aguaray'),
  ('Salta', 'Aguas Blancas'),
  ('Salta', 'Angastaco'),
  ('Salta', 'Animaná'),
  ('Salta', 'Apolinario Saravia'),
  ('Salta', 'Cachi'),
  ('Salta', 'Cafayate'),
  ('Salta', 'Campo Quijano'),
  ('Salta', 'Campo Santo'),
  ('Salta', 'Chicoana'),
  ('Salta', 'Colonia Santa Rosa'),
  ('Salta', 'Coronel Moldes'),
  ('Salta', 'El Bordo'),
  ('Salta', 'El Carril'),
  ('Salta', 'El Galpón'),
  ('Salta', 'El Jardín'),
  ('Salta', 'El Potrero'),
  ('Salta', 'El Quebrachal'),
  ('Salta', 'El Tala'),
  ('Salta', 'Embarcación'),
  ('Salta', 'General Ballivián'),
  ('Salta', 'General Güemes'),
  ('Salta', 'General Mosconi'),
  ('Salta', 'General Pizarro'),
  ('Salta', 'Guachipas'),
  ('Salta', 'Hipólito Yrigoyen'),
  ('Salta', 'Iruya'),
  ('Salta', 'Isla de Cañas'),
  ('Salta', 'Joaquín V. González'),
  ('Salta', 'La Caldera'),
  ('Salta', 'La Candelaria'),
  ('Salta', 'La Merced'),
  ('Salta', 'La Poma'),
  ('Salta', 'La Viña'),
  ('Salta', 'Las Lajitas'),
  ('Salta', 'Los Toldos'),
  ('Salta', 'Molinos'),
  ('Salta', 'Nazareno'),
  ('Salta', 'Payogasta'),
  ('Salta', 'Pichanal'),
  ('Salta', 'Profesor Salvador Mazza'),
  ('Salta', 'Río Piedras'),
  ('Salta', 'Rivadavia Banda Norte'),
  ('Salta', 'Rivadavia Banda Sur'),
  ('Salta', 'Rosario de la Frontera'),
  ('Salta', 'Rosario de Lerma'),
  ('Salta', 'Salta'),
  ('Salta', 'San Antonio de los Cobres'),
  ('Salta', 'San Carlos'),
  ('Salta', 'San José de los Cerrillos'),
  ('Salta', 'San José de Metán'),
  ('Salta', 'San Lorenzo'),
  ('Salta', 'San Ramón de la Nueva Orán'),
  ('Salta', 'Santa Victoria Este'),
  ('Salta', 'Santa Victoria Oeste'),
  ('Salta', 'Seclantás'),
  ('Salta', 'Tartagal'),
  ('Salta', 'Tolar Grande'),
  ('Salta', 'Urundel'),
  ('Salta', 'Vaqueros'),
  ('San Juan', '25 de Mayo'),
  ('San Juan', '9 de Julio'),
  ('San Juan', 'Albardón'),
  ('San Juan', 'Angaco'),
  ('San Juan', 'Calingasta'),
  ('San Juan', 'Caucete'),
  ('San Juan', 'Chimbas'),
  ('San Juan', 'Iglesia'),
  ('San Juan', 'Jáchal'),
  ('San Juan', 'Pocito'),
  ('San Juan', 'Rawson'),
  ('San Juan', 'Rivadavia'),
  ('San Juan', 'San Juan'),
  ('San Juan', 'San Martín'),
  ('San Juan', 'Santa Lucía'),
  ('San Juan', 'Sarmiento'),
  ('San Juan', 'Ullum'),
  ('San Juan', 'Valle Fértil'),
  ('San Juan', 'Zonda'),
  ('San Luis', 'Alto Pelado'),
  ('San Luis', 'Alto Pencoso'),
  ('San Luis', 'Anchorena'),
  ('San Luis', 'Arizona'),
  ('San Luis', 'Bagual'),
  ('San Luis', 'Balde'),
  ('San Luis', 'Batavia'),
  ('San Luis', 'Beazley'),
  ('San Luis', 'Buena Esperanza'),
  ('San Luis', 'Candelaria'),
  ('San Luis', 'Carpintería'),
  ('San Luis', 'Concarán'),
  ('San Luis', 'Cortaderas'),
  ('San Luis', 'Desaguadero'),
  ('San Luis', 'El Trapiche'),
  ('San Luis', 'El Volcán'),
  ('San Luis', 'Estancia Grande'),
  ('San Luis', 'Fortín El Patria'),
  ('San Luis', 'Fortuna'),
  ('San Luis', 'Fraga'),
  ('San Luis', 'Juan Jorba'),
  ('San Luis', 'Juan Llerena'),
  ('San Luis', 'Juana Koslay'),
  ('San Luis', 'Justo Daract'),
  ('San Luis', 'La Calera'),
  ('San Luis', 'La Carolina'),
  ('San Luis', 'La Punilla'),
  ('San Luis', 'La Punta'),
  ('San Luis', 'La Toma'),
  ('San Luis', 'La Vertiente'),
  ('San Luis', 'Lafinur'),
  ('San Luis', 'Las Aguadas'),
  ('San Luis', 'Las Chacras'),
  ('San Luis', 'Las Lagunas'),
  ('San Luis', 'Lavaisse'),
  ('San Luis', 'Leandro N. Alem'),
  ('San Luis', 'Los Manantiales'),
  ('San Luis', 'Los Molles'),
  ('San Luis', 'Luján'),
  ('San Luis', 'Nación Ranquel'),
  ('San Luis', 'Naschel'),
  ('San Luis', 'Navia'),
  ('San Luis', 'Nogolí'),
  ('San Luis', 'Nueva Galia'),
  ('San Luis', 'Papagayos'),
  ('San Luis', 'Paso Grande'),
  ('San Luis', 'Potrero de los Funes'),
  ('San Luis', 'Quines'),
  ('San Luis', 'Renca'),
  ('San Luis', 'Saladillo'),
  ('San Luis', 'San Francisco'),
  ('San Luis', 'San Jerónimo'),
  ('San Luis', 'San José del Morro'),
  ('San Luis', 'San Luis'),
  ('San Luis', 'San Martín'),
  ('San Luis', 'San Pablo'),
  ('San Luis', 'Santa Rosa'),
  ('San Luis', 'Talita'),
  ('San Luis', 'Tilisarao'),
  ('San Luis', 'Unión'),
  ('San Luis', 'Villa de la Quebrada'),
  ('San Luis', 'Villa de Merlo'),
  ('San Luis', 'Villa de Praga'),
  ('San Luis', 'Villa del Carmen'),
  ('San Luis', 'Villa Larca'),
  ('San Luis', 'Villa Mercedes'),
  ('San Luis', 'Zanjitas'),
  ('Santa Cruz', '28 de Noviembre'),
  ('Santa Cruz', 'Bajo Caracoles'),
  ('Santa Cruz', 'Caleta Olivia'),
  ('Santa Cruz', 'Cañadón Seco'),
  ('Santa Cruz', 'Comandante Luis Piedrabuena'),
  ('Santa Cruz', 'El Calafate'),
  ('Santa Cruz', 'El Chaltén'),
  ('Santa Cruz', 'El Turbio'),
  ('Santa Cruz', 'Fitz Roy'),
  ('Santa Cruz', 'Gobernador Gregores'),
  ('Santa Cruz', 'Hipólito Yrigoyen'),
  ('Santa Cruz', 'Jaramillo'),
  ('Santa Cruz', 'Julia Dufour'),
  ('Santa Cruz', 'Koluel Kaike'),
  ('Santa Cruz', 'Las Heras'),
  ('Santa Cruz', 'Los Antiguos'),
  ('Santa Cruz', 'Perito Moreno'),
  ('Santa Cruz', 'Pico Truncado'),
  ('Santa Cruz', 'Puerto Deseado'),
  ('Santa Cruz', 'Puerto San Julián'),
  ('Santa Cruz', 'Puerto Santa Cruz'),
  ('Santa Cruz', 'Río Gallegos'),
  ('Santa Cruz', 'Rospentek'),
  ('Santa Cruz', 'Tellier'),
  ('Santa Cruz', 'Tres Lagos'),
  ('Santa Cruz', 'Yacimientos Río Turbio'),
  ('Santa Fe', 'Aarón Castellanos'),
  ('Santa Fe', 'Acebal'),
  ('Santa Fe', 'Aguará Grande'),
  ('Santa Fe', 'Albarellos'),
  ('Santa Fe', 'Alcorta'),
  ('Santa Fe', 'Aldao'),
  ('Santa Fe', 'Alejandra'),
  ('Santa Fe', 'Álvarez'),
  ('Santa Fe', 'Alvear'),
  ('Santa Fe', 'Ambrosetti'),
  ('Santa Fe', 'Amenábar'),
  ('Santa Fe', 'Angélica'),
  ('Santa Fe', 'Angeloni'),
  ('Santa Fe', 'Arequito'),
  ('Santa Fe', 'Arminda'),
  ('Santa Fe', 'Armstrong'),
  ('Santa Fe', 'Arocena'),
  ('Santa Fe', 'Arroyo Aguiar'),
  ('Santa Fe', 'Arroyo Ceibal'),
  ('Santa Fe', 'Arroyo Leyes'),
  ('Santa Fe', 'Arroyo Seco'),
  ('Santa Fe', 'Arrufo'),
  ('Santa Fe', 'Arteaga'),
  ('Santa Fe', 'Ataliva'),
  ('Santa Fe', 'Aurelia'),
  ('Santa Fe', 'Avellaneda'),
  ('Santa Fe', 'Barrancas'),
  ('Santa Fe', 'Bauer y Sigel'),
  ('Santa Fe', 'Bella Italia'),
  ('Santa Fe', 'Berabevú'),
  ('Santa Fe', 'Berna'),
  ('Santa Fe', 'Bernardo de Irigoyen'),
  ('Santa Fe', 'Bigand'),
  ('Santa Fe', 'Bombal'),
  ('Santa Fe', 'Bouquet'),
  ('Santa Fe', 'Bustinza'),
  ('Santa Fe', 'Cabal'),
  ('Santa Fe', 'Cacique Ariacaiquín'),
  ('Santa Fe', 'Cafferata'),
  ('Santa Fe', 'Calchaquí'),
  ('Santa Fe', 'Campo Andino'),
  ('Santa Fe', 'Campo Piaggio'),
  ('Santa Fe', 'Candioti'),
  ('Santa Fe', 'Cañada de Gómez'),
  ('Santa Fe', 'Cañada del Ucle'),
  ('Santa Fe', 'Cañada Ombú'),
  ('Santa Fe', 'Cañada Rica'),
  ('Santa Fe', 'Cañada Rosquín'),
  ('Santa Fe', 'Capitán Bermúdez'),
  ('Santa Fe', 'Capivara'),
  ('Santa Fe', 'Carcarañá'),
  ('Santa Fe', 'Carlos Pellegrini'),
  ('Santa Fe', 'Carmen'),
  ('Santa Fe', 'Carmen del Sauce'),
  ('Santa Fe', 'Carreras'),
  ('Santa Fe', 'Carrizales'),
  ('Santa Fe', 'Casalegno'),
  ('Santa Fe', 'Casas'),
  ('Santa Fe', 'Casilda'),
  ('Santa Fe', 'Castelar'),
  ('Santa Fe', 'Castellanos'),
  ('Santa Fe', 'Cavour'),
  ('Santa Fe', 'Cayastá'),
  ('Santa Fe', 'Cayastacito'),
  ('Santa Fe', 'Centeno'),
  ('Santa Fe', 'Cepeda'),
  ('Santa Fe', 'Ceres'),
  ('Santa Fe', 'Chabas'),
  ('Santa Fe', 'Chañar Ladeado'),
  ('Santa Fe', 'Chapuy'),
  ('Santa Fe', 'Chovet'),
  ('Santa Fe', 'Christophersen'),
  ('Santa Fe', 'Classon'),
  ('Santa Fe', 'Colonia Aldao'),
  ('Santa Fe', 'Colonia Ana'),
  ('Santa Fe', 'Colonia Belgrano'),
  ('Santa Fe', 'Colonia Bicha'),
  ('Santa Fe', 'Colonia Bigand'),
  ('Santa Fe', 'Colonia Bossi'),
  ('Santa Fe', 'Colonia Cello'),
  ('Santa Fe', 'Colonia Clara'),
  ('Santa Fe', 'Colonia Dolores'),
  ('Santa Fe', 'Colonia Durán'),
  ('Santa Fe', 'Colonia Iturraspe'),
  ('Santa Fe', 'Colonia Margarita'),
  ('Santa Fe', 'Colonia Mascías'),
  ('Santa Fe', 'Colonia Maua'),
  ('Santa Fe', 'Colonia Raquel'),
  ('Santa Fe', 'Colonia Rosa'),
  ('Santa Fe', 'Constanza'),
  ('Santa Fe', 'Coronda'),
  ('Santa Fe', 'Coronel Arnold'),
  ('Santa Fe', 'Coronel Bogado'),
  ('Santa Fe', 'Coronel Domínguez'),
  ('Santa Fe', 'Coronel Fraga'),
  ('Santa Fe', 'Correa'),
  ('Santa Fe', 'Crispi'),
  ('Santa Fe', 'Cululú'),
  ('Santa Fe', 'Curupaity'),
  ('Santa Fe', 'Desvío Arijón'),
  ('Santa Fe', 'Díaz'),
  ('Santa Fe', 'Diego de Alvear'),
  ('Santa Fe', 'Dos Rosas y La Legua'),
  ('Santa Fe', 'Egusquiza'),
  ('Santa Fe', 'El Araza'),
  ('Santa Fe', 'El Rabón'),
  ('Santa Fe', 'El Sombrerito'),
  ('Santa Fe', 'El Trébol'),
  ('Santa Fe', 'Elisa'),
  ('Santa Fe', 'Elortondo'),
  ('Santa Fe', 'Emilia'),
  ('Santa Fe', 'Empalme San Carlos'),
  ('Santa Fe', 'Empalme Villa Constitución'),
  ('Santa Fe', 'Esmeralda'),
  ('Santa Fe', 'Esperanza'),
  ('Santa Fe', 'Estación Clucellas'),
  ('Santa Fe', 'Esteban Rams'),
  ('Santa Fe', 'Esther'),
  ('Santa Fe', 'Eusebia y Carolina'),
  ('Santa Fe', 'Eustolia'),
  ('Santa Fe', 'Felicia'),
  ('Santa Fe', 'Fidela'),
  ('Santa Fe', 'Fighiera'),
  ('Santa Fe', 'Firmat'),
  ('Santa Fe', 'Florencia'),
  ('Santa Fe', 'Fortín Olmos'),
  ('Santa Fe', 'Franck'),
  ('Santa Fe', 'Fray Luis Beltrán'),
  ('Santa Fe', 'Frontera'),
  ('Santa Fe', 'Fuentes'),
  ('Santa Fe', 'Funes'),
  ('Santa Fe', 'Gaboto'),
  ('Santa Fe', 'Galisteo'),
  ('Santa Fe', 'Gálvez'),
  ('Santa Fe', 'Garabato'),
  ('Santa Fe', 'Garibaldi'),
  ('Santa Fe', 'Gato Colorado'),
  ('Santa Fe', 'General Gelly'),
  ('Santa Fe', 'General Lagos'),
  ('Santa Fe', 'Gessler'),
  ('Santa Fe', 'Gobernador Crespo'),
  ('Santa Fe', 'Gödeken'),
  ('Santa Fe', 'Godoy'),
  ('Santa Fe', 'Golondrina'),
  ('Santa Fe', 'Granadero Baigorria'),
  ('Santa Fe', 'Gregoria Pérez de Denis'),
  ('Santa Fe', 'Grutly'),
  ('Santa Fe', 'Guadalupe Norte'),
  ('Santa Fe', 'Helvecia'),
  ('Santa Fe', 'Hersilia'),
  ('Santa Fe', 'Hipatía'),
  ('Santa Fe', 'Huanqueros'),
  ('Santa Fe', 'Hugentobler'),
  ('Santa Fe', 'Hughes'),
  ('Santa Fe', 'Humberto Primo'),
  ('Santa Fe', 'Humboldt'),
  ('Santa Fe', 'Ibarlucea'),
  ('Santa Fe', 'Ingeniero Chanourdie'),
  ('Santa Fe', 'Intiyaco'),
  ('Santa Fe', 'Irigoyen'),
  ('Santa Fe', 'Ituzaingó'),
  ('Santa Fe', 'Jacinto L. Aráuz'),
  ('Santa Fe', 'Josefina'),
  ('Santa Fe', 'Juan B. Molina'),
  ('Santa Fe', 'Juan de Garay'),
  ('Santa Fe', 'Juncal'),
  ('Santa Fe', 'La Brava'),
  ('Santa Fe', 'La Cabral'),
  ('Santa Fe', 'La Camila'),
  ('Santa Fe', 'La Chispa'),
  ('Santa Fe', 'La Criolla'),
  ('Santa Fe', 'La Gallareta'),
  ('Santa Fe', 'La Lucila'),
  ('Santa Fe', 'La Pelada'),
  ('Santa Fe', 'La Penca y Caraguatá'),
  ('Santa Fe', 'La Rubia'),
  ('Santa Fe', 'La Sarita'),
  ('Santa Fe', 'La Vanguardia'),
  ('Santa Fe', 'Labordeboy'),
  ('Santa Fe', 'Laguna Paiva'),
  ('Santa Fe', 'Landeta'),
  ('Santa Fe', 'Lanteri'),
  ('Santa Fe', 'Larrechea'),
  ('Santa Fe', 'Las Avispas'),
  ('Santa Fe', 'Las Bandurrias'),
  ('Santa Fe', 'Las Garzas'),
  ('Santa Fe', 'Las Palmeras'),
  ('Santa Fe', 'Las Parejas'),
  ('Santa Fe', 'Las Petacas'),
  ('Santa Fe', 'Las Rosas'),
  ('Santa Fe', 'Las Toscas'),
  ('Santa Fe', 'Las Tunas'),
  ('Santa Fe', 'Lazzarino'),
  ('Santa Fe', 'Lehmann'),
  ('Santa Fe', 'Llambí Campbell'),
  ('Santa Fe', 'Logroño'),
  ('Santa Fe', 'Loma Alta'),
  ('Santa Fe', 'López'),
  ('Santa Fe', 'Los Amores'),
  ('Santa Fe', 'Los Cardos'),
  ('Santa Fe', 'Los Laureles'),
  ('Santa Fe', 'Los Molinos'),
  ('Santa Fe', 'Los Quirquinchos'),
  ('Santa Fe', 'Los Tábanos'),
  ('Santa Fe', 'Lucio V. López'),
  ('Santa Fe', 'Luis Palacios'),
  ('Santa Fe', 'Maciel'),
  ('Santa Fe', 'Maggiolo'),
  ('Santa Fe', 'Malabrigo'),
  ('Santa Fe', 'Marcelino Escalada'),
  ('Santa Fe', 'Margarita'),
  ('Santa Fe', 'María Juana'),
  ('Santa Fe', 'María Luisa'),
  ('Santa Fe', 'María Susana'),
  ('Santa Fe', 'María Teresa'),
  ('Santa Fe', 'Matilde'),
  ('Santa Fe', 'Máximo Paz'),
  ('Santa Fe', 'Melincué'),
  ('Santa Fe', 'Miguel Torres'),
  ('Santa Fe', 'Moisés Ville'),
  ('Santa Fe', 'Monigotes'),
  ('Santa Fe', 'Monje'),
  ('Santa Fe', 'Monte Oscuridad'),
  ('Santa Fe', 'Monte Vera'),
  ('Santa Fe', 'Montefiore'),
  ('Santa Fe', 'Montes de Oca'),
  ('Santa Fe', 'Murphy'),
  ('Santa Fe', 'Naré'),
  ('Santa Fe', 'Nelson'),
  ('Santa Fe', 'Nicanor Molinas'),
  ('Santa Fe', 'Nuevo Torino'),
  ('Santa Fe', 'Ñanducita'),
  ('Santa Fe', 'Oliveros'),
  ('Santa Fe', 'Palacios'),
  ('Santa Fe', 'Pavón'),
  ('Santa Fe', 'Pavón Arriba'),
  ('Santa Fe', 'Pedro Gómez Cello'),
  ('Santa Fe', 'Pérez'),
  ('Santa Fe', 'Peyrano'),
  ('Santa Fe', 'Piamonte'),
  ('Santa Fe', 'Pilar'),
  ('Santa Fe', 'Piñero'),
  ('Santa Fe', 'Plaza Clucellas'),
  ('Santa Fe', 'Portugalete'),
  ('Santa Fe', 'Pozo Borrado'),
  ('Santa Fe', 'Presidente Roca'),
  ('Santa Fe', 'Progreso'),
  ('Santa Fe', 'Providencia'),
  ('Santa Fe', 'Pueblo Andino'),
  ('Santa Fe', 'Pueblo Esther'),
  ('Santa Fe', 'Pueblo Marini'),
  ('Santa Fe', 'Pueblo Muñoz'),
  ('Santa Fe', 'Puerto General San Martín'),
  ('Santa Fe', 'Pujato'),
  ('Santa Fe', 'Pujato Norte'),
  ('Santa Fe', 'Rafaela'),
  ('Santa Fe', 'Ramayón'),
  ('Santa Fe', 'Ramona'),
  ('Santa Fe', 'Reconquista'),
  ('Santa Fe', 'Recreo'),
  ('Santa Fe', 'Ricardone'),
  ('Santa Fe', 'Rivadavia'),
  ('Santa Fe', 'Roldán'),
  ('Santa Fe', 'Romang'),
  ('Santa Fe', 'Rosario'),
  ('Santa Fe', 'Rueda'),
  ('Santa Fe', 'Rufino'),
  ('Santa Fe', 'Sa Pereyra'),
  ('Santa Fe', 'Saguier'),
  ('Santa Fe', 'Saladero Mariano Cabal'),
  ('Santa Fe', 'Salto Grande'),
  ('Santa Fe', 'San Agustín'),
  ('Santa Fe', 'San Antonio'),
  ('Santa Fe', 'San Antonio de Obligado'),
  ('Santa Fe', 'San Bernardo'),
  ('Santa Fe', 'San Carlos Centro'),
  ('Santa Fe', 'San Carlos Norte'),
  ('Santa Fe', 'San Carlos Sud'),
  ('Santa Fe', 'San Cristóbal'),
  ('Santa Fe', 'San Eduardo'),
  ('Santa Fe', 'San Eugenio'),
  ('Santa Fe', 'San Fabián'),
  ('Santa Fe', 'San Francisco de Santa Fe'),
  ('Santa Fe', 'San Genaro'),
  ('Santa Fe', 'San Gregorio'),
  ('Santa Fe', 'San Guillermo'),
  ('Santa Fe', 'San Javier'),
  ('Santa Fe', 'San Jerónimo del Sauce'),
  ('Santa Fe', 'San Jerónimo Norte'),
  ('Santa Fe', 'San Jerónimo Sud'),
  ('Santa Fe', 'San Jorge'),
  ('Santa Fe', 'San José'),
  ('Santa Fe', 'San José de la Esquina'),
  ('Santa Fe', 'San José del Rincón'),
  ('Santa Fe', 'San Justo'),
  ('Santa Fe', 'San Lorenzo'),
  ('Santa Fe', 'San Mariano'),
  ('Santa Fe', 'San Martín de las Escobas'),
  ('Santa Fe', 'San Martín Norte'),
  ('Santa Fe', 'San Vicente'),
  ('Santa Fe', 'Sancti Spiritu'),
  ('Santa Fe', 'Sanford'),
  ('Santa Fe', 'Santa Clara de Buena Vista'),
  ('Santa Fe', 'Santa Clara de Saguier'),
  ('Santa Fe', 'Santa Fe'),
  ('Santa Fe', 'Santa Isabel'),
  ('Santa Fe', 'Santa Margarita'),
  ('Santa Fe', 'Santa María Centro'),
  ('Santa Fe', 'Santa María Norte'),
  ('Santa Fe', 'Santa Rosa de Calchines'),
  ('Santa Fe', 'Santa Teresa'),
  ('Santa Fe', 'Santo Domingo'),
  ('Santa Fe', 'Santo Tomé'),
  ('Santa Fe', 'Santurce'),
  ('Santa Fe', 'Sargento Cabral'),
  ('Santa Fe', 'Sarmiento'),
  ('Santa Fe', 'Sastre y Ortiz'),
  ('Santa Fe', 'Sauce Viejo'),
  ('Santa Fe', 'Serodino'),
  ('Santa Fe', 'Silva'),
  ('Santa Fe', 'Soldini'),
  ('Santa Fe', 'Soledad'),
  ('Santa Fe', 'Soutomayor'),
  ('Santa Fe', 'Suardi'),
  ('Santa Fe', 'Sunchales'),
  ('Santa Fe', 'Susana'),
  ('Santa Fe', 'Tacuarendi'),
  ('Santa Fe', 'Tacural'),
  ('Santa Fe', 'Tacurales'),
  ('Santa Fe', 'Tartagal'),
  ('Santa Fe', 'Teodelina'),
  ('Santa Fe', 'Theobald'),
  ('Santa Fe', 'Timbúes'),
  ('Santa Fe', 'Toba'),
  ('Santa Fe', 'Tortugas'),
  ('Santa Fe', 'Tostado'),
  ('Santa Fe', 'Totoras'),
  ('Santa Fe', 'Traill'),
  ('Santa Fe', 'Uranga'),
  ('Santa Fe', 'Venado Tuerto'),
  ('Santa Fe', 'Vera'),
  ('Santa Fe', 'Vera y Pintado'),
  ('Santa Fe', 'Videla'),
  ('Santa Fe', 'Vila'),
  ('Santa Fe', 'Villa Amelia'),
  ('Santa Fe', 'Villa Ana'),
  ('Santa Fe', 'Villa Cañás'),
  ('Santa Fe', 'Villa Constitución'),
  ('Santa Fe', 'Villa Eloísa'),
  ('Santa Fe', 'Villa Gobernador Gálvez'),
  ('Santa Fe', 'Villa Guillermina'),
  ('Santa Fe', 'Villa Minetti'),
  ('Santa Fe', 'Villa Mugueta'),
  ('Santa Fe', 'Villa Ocampo'),
  ('Santa Fe', 'Villa San José'),
  ('Santa Fe', 'Villa Saralegui'),
  ('Santa Fe', 'Villa Trinidad'),
  ('Santa Fe', 'Villada'),
  ('Santa Fe', 'Virginia'),
  ('Santa Fe', 'Wheelwright'),
  ('Santa Fe', 'Zavalla'),
  ('Santa Fe', 'Zenón Pereyra'),
  ('Santiago del Estero', 'Abra Grande'),
  ('Santiago del Estero', 'Aerolito'),
  ('Santiago del Estero', 'Alhuampa'),
  ('Santiago del Estero', 'Ancaján'),
  ('Santiago del Estero', 'Antajé'),
  ('Santiago del Estero', 'Añatuya'),
  ('Santiago del Estero', 'Ardiles'),
  ('Santiago del Estero', 'Argentina'),
  ('Santiago del Estero', 'Árraga'),
  ('Santiago del Estero', 'Averías'),
  ('Santiago del Estero', 'Bandera'),
  ('Santiago del Estero', 'Bandera Bajada'),
  ('Santiago del Estero', 'Beltrán'),
  ('Santiago del Estero', 'Brea Pozo'),
  ('Santiago del Estero', 'Campo Gallo'),
  ('Santiago del Estero', 'Cañada Escobar'),
  ('Santiago del Estero', 'Casares'),
  ('Santiago del Estero', 'Caspi Corral'),
  ('Santiago del Estero', 'Chauchillas'),
  ('Santiago del Estero', 'Chaupi Pozo'),
  ('Santiago del Estero', 'Chilca Juliana'),
  ('Santiago del Estero', 'Choya'),
  ('Santiago del Estero', 'Clodomira'),
  ('Santiago del Estero', 'Colonia Alpina'),
  ('Santiago del Estero', 'Colonia Dora'),
  ('Santiago del Estero', 'Colonia El Simbolar'),
  ('Santiago del Estero', 'Colonia San Juan'),
  ('Santiago del Estero', 'Colonia Tinco'),
  ('Santiago del Estero', 'Coronel Manuel L. Rico'),
  ('Santiago del Estero', 'Cuatro Bocas'),
  ('Santiago del Estero', 'Donadeu'),
  ('Santiago del Estero', 'El 49'),
  ('Santiago del Estero', 'El Arenal'),
  ('Santiago del Estero', 'El Bobadal'),
  ('Santiago del Estero', 'El Caburé'),
  ('Santiago del Estero', 'El Charco'),
  ('Santiago del Estero', 'El Colorado'),
  ('Santiago del Estero', 'El Crucero'),
  ('Santiago del Estero', 'El Cuadrado'),
  ('Santiago del Estero', 'El Deán'),
  ('Santiago del Estero', 'El Mojón'),
  ('Santiago del Estero', 'El Rincón'),
  ('Santiago del Estero', 'El Sauzal'),
  ('Santiago del Estero', 'El Zanjón'),
  ('Santiago del Estero', 'Estación Atamisqui'),
  ('Santiago del Estero', 'Estación La Punta'),
  ('Santiago del Estero', 'Estación Robles'),
  ('Santiago del Estero', 'Estación Taboada'),
  ('Santiago del Estero', 'Estación Tacañitas'),
  ('Santiago del Estero', 'Fernández'),
  ('Santiago del Estero', 'Fortín Inca'),
  ('Santiago del Estero', 'Frías'),
  ('Santiago del Estero', 'Garza'),
  ('Santiago del Estero', 'Gramilla'),
  ('Santiago del Estero', 'Guardia Escolta'),
  ('Santiago del Estero', 'Hasse'),
  ('Santiago del Estero', 'Hernán Mejía Miraval'),
  ('Santiago del Estero', 'Herrera'),
  ('Santiago del Estero', 'Huyamampa'),
  ('Santiago del Estero', 'Icaño'),
  ('Santiago del Estero', 'Ingeniero Forres'),
  ('Santiago del Estero', 'Isca Yacu'),
  ('Santiago del Estero', 'Isca Yacu Semaul'),
  ('Santiago del Estero', 'La Aurora'),
  ('Santiago del Estero', 'La Banda'),
  ('Santiago del Estero', 'La Cañada'),
  ('Santiago del Estero', 'La Dársena'),
  ('Santiago del Estero', 'La Invernada'),
  ('Santiago del Estero', 'La Nena'),
  ('Santiago del Estero', 'La Nueva Donosa'),
  ('Santiago del Estero', 'Laprida'),
  ('Santiago del Estero', 'Las Delicias'),
  ('Santiago del Estero', 'Las Tinajas'),
  ('Santiago del Estero', 'Lavalle'),
  ('Santiago del Estero', 'Libertad'),
  ('Santiago del Estero', 'Lilo Viejo'),
  ('Santiago del Estero', 'Los Cardozos'),
  ('Santiago del Estero', 'Los Juríes'),
  ('Santiago del Estero', 'Los Miranda'),
  ('Santiago del Estero', 'Los Núñez'),
  ('Santiago del Estero', 'Los Pirpintos'),
  ('Santiago del Estero', 'Los Quiroga'),
  ('Santiago del Estero', 'Los Soria'),
  ('Santiago del Estero', 'Los Telares'),
  ('Santiago del Estero', 'Los Tigres'),
  ('Santiago del Estero', 'Lugones'),
  ('Santiago del Estero', 'Maco'),
  ('Santiago del Estero', 'Malbrán'),
  ('Santiago del Estero', 'Mansupa'),
  ('Santiago del Estero', 'Maquito'),
  ('Santiago del Estero', 'Matará'),
  ('Santiago del Estero', 'Medellín'),
  ('Santiago del Estero', 'Minerva'),
  ('Santiago del Estero', 'Monte Quemado'),
  ('Santiago del Estero', 'Morales'),
  ('Santiago del Estero', 'Nueva Esperanza'),
  ('Santiago del Estero', 'Nueva Francia'),
  ('Santiago del Estero', 'Palo Negro'),
  ('Santiago del Estero', 'Pampa de los Guanacos'),
  ('Santiago del Estero', 'Patay'),
  ('Santiago del Estero', 'Pozo Betbeder'),
  ('Santiago del Estero', 'Pozo Hondo'),
  ('Santiago del Estero', 'Pozuelos'),
  ('Santiago del Estero', 'Pueblo Pablo Torelo'),
  ('Santiago del Estero', 'Puesto de San Antonio'),
  ('Santiago del Estero', 'Quimili'),
  ('Santiago del Estero', 'Ramírez de Velazco'),
  ('Santiago del Estero', 'Rapelli'),
  ('Santiago del Estero', 'Real Sayana'),
  ('Santiago del Estero', 'Rodeo de Valdez'),
  ('Santiago del Estero', 'Roversi'),
  ('Santiago del Estero', 'Sachayoj'),
  ('Santiago del Estero', 'San José del Boquerón'),
  ('Santiago del Estero', 'San Pedro'),
  ('Santiago del Estero', 'Santa María'),
  ('Santiago del Estero', 'Santiago del Estero'),
  ('Santiago del Estero', 'Santo Domingo'),
  ('Santiago del Estero', 'Santos Lugares'),
  ('Santiago del Estero', 'Selva'),
  ('Santiago del Estero', 'Simbol'),
  ('Santiago del Estero', 'Simbolar'),
  ('Santiago del Estero', 'Sol de Julio'),
  ('Santiago del Estero', 'Sumamao'),
  ('Santiago del Estero', 'Sumampa'),
  ('Santiago del Estero', 'Sumampa Viejo'),
  ('Santiago del Estero', 'Suncho Corral'),
  ('Santiago del Estero', 'Tapso'),
  ('Santiago del Estero', 'Termas de Río Hondo'),
  ('Santiago del Estero', 'Tintina'),
  ('Santiago del Estero', 'Tomás Young'),
  ('Santiago del Estero', 'Tramo 16'),
  ('Santiago del Estero', 'Tramo 20'),
  ('Santiago del Estero', 'Urutaú'),
  ('Santiago del Estero', 'Vaca Huañuna'),
  ('Santiago del Estero', 'Vilelas'),
  ('Santiago del Estero', 'Villa Atamisqui'),
  ('Santiago del Estero', 'Villa Figueroa'),
  ('Santiago del Estero', 'Villa General Mitre'),
  ('Santiago del Estero', 'Villa Giménez'),
  ('Santiago del Estero', 'Villa La Punta'),
  ('Santiago del Estero', 'Villa Mailín'),
  ('Santiago del Estero', 'Villa Nueva'),
  ('Santiago del Estero', 'Villa Ojo de Agua'),
  ('Santiago del Estero', 'Villa Río Hondo'),
  ('Santiago del Estero', 'Villa Salavina'),
  ('Santiago del Estero', 'Villa San Martín (Est. Loreto)'),
  ('Santiago del Estero', 'Villa Silípica'),
  ('Santiago del Estero', 'Villa Unión'),
  ('Santiago del Estero', 'Vilmer'),
  ('Santiago del Estero', 'Vinará'),
  ('Santiago del Estero', 'Vuelta de la Barranca'),
  ('Santiago del Estero', 'Weisburd'),
  ('Santiago del Estero', 'Yanda'),
  ('Santiago del Estero', 'Yuchán'),
  ('Tierra del Fuego', 'Río Grande'),
  ('Tierra del Fuego', 'Tolhuin'),
  ('Tierra del Fuego', 'Ushuaia'),
  ('Tucumán', '7 de Abril'),
  ('Tucumán', 'Acheral'),
  ('Tucumán', 'Agua Dulce y La Soledad'),
  ('Tucumán', 'Aguilares'),
  ('Tucumán', 'Alderetes'),
  ('Tucumán', 'Alpachiri y El Molino'),
  ('Tucumán', 'Alto Verde y Los Guchea'),
  ('Tucumán', 'Amaicha del Valle'),
  ('Tucumán', 'Amberes'),
  ('Tucumán', 'Anca Juli'),
  ('Tucumán', 'Arcadia'),
  ('Tucumán', 'Atahona'),
  ('Tucumán', 'Banda del Río Salí'),
  ('Tucumán', 'Bella Vista'),
  ('Tucumán', 'Benjamín Aráoz y El Tajamar'),
  ('Tucumán', 'Buena Vista'),
  ('Tucumán', 'Burruyacú'),
  ('Tucumán', 'Capitán Cáceres'),
  ('Tucumán', 'Cevil Redondo'),
  ('Tucumán', 'Choromoro'),
  ('Tucumán', 'Ciudacita'),
  ('Tucumán', 'Colalao del Valle'),
  ('Tucumán', 'Colombres'),
  ('Tucumán', 'Concepción'),
  ('Tucumán', 'Delfín Gallo'),
  ('Tucumán', 'El Bracho y El Cevilar'),
  ('Tucumán', 'El Cadillal'),
  ('Tucumán', 'El Cercado'),
  ('Tucumán', 'El Chañar'),
  ('Tucumán', 'El Manantial'),
  ('Tucumán', 'El Mojón'),
  ('Tucumán', 'El Mollar'),
  ('Tucumán', 'El Naranjito'),
  ('Tucumán', 'El Naranjo y El Sunchal'),
  ('Tucumán', 'El Polear y Los Córdoba'),
  ('Tucumán', 'El Puestito'),
  ('Tucumán', 'El Sacrificio'),
  ('Tucumán', 'El Timbó'),
  ('Tucumán', 'Escaba'),
  ('Tucumán', 'Esquina y Mancopa'),
  ('Tucumán', 'Estación Aráoz y Tacanas'),
  ('Tucumán', 'Famaillá'),
  ('Tucumán', 'Garmendia'),
  ('Tucumán', 'Gastona y Belicha'),
  ('Tucumán', 'Gobernador Piedrabuena'),
  ('Tucumán', 'Graneros'),
  ('Tucumán', 'Huasa Pampa'),
  ('Tucumán', 'Juan Bautista Alberdi'),
  ('Tucumán', 'La Cocha'),
  ('Tucumán', 'La Esperanza'),
  ('Tucumán', 'La Florida y Luisiana'),
  ('Tucumán', 'La Ramada y La Cruz'),
  ('Tucumán', 'La Trinidad'),
  ('Tucumán', 'Lamadrid'),
  ('Tucumán', 'Las Cejas'),
  ('Tucumán', 'Las Talas'),
  ('Tucumán', 'Las Talitas'),
  ('Tucumán', 'León Rouges y Santa Rosa'),
  ('Tucumán', 'Los Bulacio y Los Villagra'),
  ('Tucumán', 'Los Gómez'),
  ('Tucumán', 'Los Nogales'),
  ('Tucumán', 'Los Pereyra'),
  ('Tucumán', 'Los Pérez'),
  ('Tucumán', 'Los Puestos'),
  ('Tucumán', 'Los Ralos'),
  ('Tucumán', 'Los Sarmiento y La Tipa'),
  ('Tucumán', 'Los Sosa'),
  ('Tucumán', 'Manuel García Fernández'),
  ('Tucumán', 'Manuela Pedraza'),
  ('Tucumán', 'Medina'),
  ('Tucumán', 'Monte Bello'),
  ('Tucumán', 'Monteagudo'),
  ('Tucumán', 'Monteros'),
  ('Tucumán', 'Pampa Mayo'),
  ('Tucumán', 'Quilmes y Los Sueldos'),
  ('Tucumán', 'Raco'),
  ('Tucumán', 'Ranchillos y San Miguel'),
  ('Tucumán', 'Río Chico y Nueva Trinidad'),
  ('Tucumán', 'Río Colorado'),
  ('Tucumán', 'Río Seco'),
  ('Tucumán', 'Rumi Punco'),
  ('Tucumán', 'San Andrés'),
  ('Tucumán', 'San Felipe y Santa Bárbara'),
  ('Tucumán', 'San Ignacio'),
  ('Tucumán', 'San Isidro de Lules'),
  ('Tucumán', 'San Javier'),
  ('Tucumán', 'San José de la Cocha'),
  ('Tucumán', 'San Miguel de Tucumán'),
  ('Tucumán', 'San Pablo y Villa Nougués'),
  ('Tucumán', 'San Pedro de Colalao'),
  ('Tucumán', 'San Pedro y San Antonio'),
  ('Tucumán', 'Santa Ana'),
  ('Tucumán', 'Santa Cruz y La Tuna'),
  ('Tucumán', 'Santa Lucía'),
  ('Tucumán', 'Santa Rosa de Leales y Laguna Blanca'),
  ('Tucumán', 'Sargento Moya'),
  ('Tucumán', 'Simoca'),
  ('Tucumán', 'Soldado Maldonado'),
  ('Tucumán', 'Taco Ralo'),
  ('Tucumán', 'Tafí del Valle'),
  ('Tucumán', 'Tafí Viejo'),
  ('Tucumán', 'Tapia'),
  ('Tucumán', 'Teniente Berdina'),
  ('Tucumán', 'Trancas'),
  ('Tucumán', 'Villa Belgrano'),
  ('Tucumán', 'Villa Chicligasta'),
  ('Tucumán', 'Villa de Leales'),
  ('Tucumán', 'Villa Padre Monti'),
  ('Tucumán', 'Villa Quinteros'),
  ('Tucumán', 'Yánima y El Corralito'),
  ('Tucumán', 'Yerba Buena');

-- Ahora que provinces ya tiene datos, professionals.province puede ser un FK
-- real (no solo texto gobernado por la UI). Sin FK sobre city: admite el
-- valor especial "General" (= toda la provincia), que no es una ciudad real.
alter table public.professionals
  add constraint professionals_province_fkey
  foreign key (province) references public.provinces (id);
